syntax = "proto3";

package cloud.v1.topology;

import "cloud/v1/common/status.proto";
import "cloud/v1/common/tags.proto";
import "cloud/v1/deployment/machine.proto";
import "cloud/v1/deployment/quota.proto";
import "cloud/v1/topology/component.proto";
import "cloud/v1/topology/connection.proto";
import "schemapb/schema.proto";
import "validate/validate.proto";

option go_package = "github.com/stroppy-io/stroppy-cloud/internal/proto/cloud/v1/topology";

message Topology {
    message Instance {
        string id = 1 [(validate.rules).string = {min_len: 1, max_len: 128}];
        common.Status status = 2;
        deployment.MachineInfo machine_info = 3;
        optional schemapb.Baked provider_parms = 4; // calculated (wisard)
        repeated deployment.Quota.Request quota_requests = 5; // calculated (deployment)
        repeated deployment.Quota.Allocation allocated_quotas = 6; // calculated (deployment)
        optional schemapb.Baked deployment_parms = 7; // calculated (deployment)
        common.Tags tags = 8;
    }
    repeated Instance instances = 1 [(validate.rules).repeated.min_items = 1];
    repeated topology.Connection connections = 2 [(validate.rules).repeated.min_items = 1];
    /*
        Here we can add something like managed database or another sevice from prvider
        Responsibility of this is RenderTerraformVariablesWorkflow|RenderDockerInputWorkflow
    */
    repeated Component external_components = 3 [(validate.rules).repeated.max_items = 64];
    common.Tags tags = 4;
}