// Code generated by protoc-gen-go-plain. DO NOT EDIT.
// source: cloud/v1/catalog/package.proto

package catalog

import (
	common "github.com/stroppy-io/stroppy-cloud/internal/proto/cloud/v1/common"
	iam "github.com/stroppy-io/stroppy-cloud/internal/proto/cloud/v1/iam"
	ratelcast "github.com/yaroher/ratel/pkg/ratelcast"
	protojson "google.golang.org/protobuf/encoding/protojson"
	time "time"
)

// Package — installable unit for a specific DB engine + version on agent
// hosts. One row = one recipe (apt repo bootstrap, package list, or .deb
// blob). Builtin packages have tenant_id IS NULL.
// Source: stroppy-cloud/internal/domain/types/packages.go Package.
type PackageScanner struct {
	Id          string     `json:"id"`                 // origin: type_alias, empath: id
	TenantId    *string    `json:"tenantId,omitempty"` // origin: type_alias, empath: tenant_id
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
	DeletedAt   *time.Time `json:"deletedAt,omitempty"`
	Name        string     `json:"name"`
	Description *string    `json:"description,omitempty"`
	Label       []string   `json:"label"`
	CreatedBy   *string    `json:"createdBy,omitempty"` // origin: type_alias, empath: created_by
	DbKind      string     `json:"dbKind"`
	DbVersion   string     `json:"dbVersion"`
	IsBuiltin   bool       `json:"isBuiltin"`
	Source      []byte     `json:"source"` // origin: serialized, empath: source
}

// IntoPlain converts protobuf message to plain struct
func (pb *Package) IntoPlain() *PackageScanner {
	if pb == nil {
		return nil
	}
	p := &PackageScanner{}

	// Id type alias from id
	if pb.GetId() != nil {
		p.Id = pb.GetId().GetValue()
	}
	// TenantId type alias from tenant_id
	if pb.GetTenantId() != nil {
		_tmp := pb.GetTenantId().GetValue()
		p.TenantId = &_tmp
	}
	// CreatedAt from
	if pb.GetTimestamps() != nil && pb.GetTimestamps().GetCreatedAt() != nil {
		p.CreatedAt = ratelcast.TimestampToTime(pb.GetTimestamps().GetCreatedAt())
	}
	// UpdatedAt from
	if pb.GetTimestamps() != nil && pb.GetTimestamps().GetUpdatedAt() != nil {
		p.UpdatedAt = ratelcast.TimestampToTime(pb.GetTimestamps().GetUpdatedAt())
	}
	// DeletedAt from
	if pb.GetTimestamps() != nil && pb.GetTimestamps().GetDeletedAt() != nil {
		_tmp := ratelcast.TimestampToTime(pb.GetTimestamps().GetDeletedAt())
		p.DeletedAt = &_tmp
	}
	// Name from
	if pb.GetIdentity() != nil {
		p.Name = pb.GetIdentity().GetName()
	}
	// Description from
	if pb.GetIdentity() != nil {
		_tmp := pb.GetIdentity().GetDescription()
		p.Description = &_tmp
	}
	// Label from
	if pb.GetIdentity() != nil && pb.GetIdentity().GetLabels() != nil {
		if len(pb.GetIdentity().GetLabels().GetLabel()) > 0 {
			p.Label = pb.GetIdentity().GetLabels().GetLabel()
		} else {
			p.Label = []string{}
		}
	}
	// CreatedBy type alias from created_by
	if pb.GetCreatedBy() != nil {
		_tmp := pb.GetCreatedBy().GetValue()
		p.CreatedBy = &_tmp
	}
	p.DbKind = pb.DbKind.String()
	p.DbVersion = pb.DbVersion
	p.IsBuiltin = pb.IsBuiltin
	// Source serialized from source
	if pb.Source != nil {
		if data, err := protojson.Marshal(pb.Source); err == nil {
			p.Source = data
		}
	} else {
		p.Source = []byte{}
	}
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *PackageScanner) IntoPb() *Package {
	if p == nil {
		return nil
	}
	pb := &Package{}

	// Id type alias -> id
	if p.Id != "" {
		pb.Id = &PackageId{Value: p.Id}
	}
	// TenantId type alias -> tenant_id
	if p.TenantId != nil {
		pb.TenantId = &iam.TenantId{Value: *p.TenantId}
	}
	// CreatedAt ->
	if pb.Timestamps == nil {
		pb.Timestamps = &common.Timestamps{}
	}
	pb.Timestamps.CreatedAt = ratelcast.TimeToTimestamp(p.CreatedAt)
	// UpdatedAt ->
	if pb.Timestamps == nil {
		pb.Timestamps = &common.Timestamps{}
	}
	pb.Timestamps.UpdatedAt = ratelcast.TimeToTimestamp(p.UpdatedAt)
	// DeletedAt ->
	if p.DeletedAt != nil {
		if pb.Timestamps == nil {
			pb.Timestamps = &common.Timestamps{}
		}
		pb.Timestamps.DeletedAt = ratelcast.TimeToTimestamp(*p.DeletedAt)
	}
	// Name ->
	if p.Name != "" {
		if pb.Identity == nil {
			pb.Identity = &common.Identity{}
		}
		pb.Identity.Name = p.Name
	}
	// Description ->
	if p.Description != nil {
		if pb.Identity == nil {
			pb.Identity = &common.Identity{}
		}
		pb.Identity.Description = p.Description
	}
	// Label ->
	if len(p.Label) > 0 {
		if pb.Identity == nil {
			pb.Identity = &common.Identity{}
		}
		if pb.Identity.Labels == nil {
			pb.Identity.Labels = &common.Labels{}
		}
		pb.Identity.Labels.Label = p.Label
	}
	// CreatedBy type alias -> created_by
	if p.CreatedBy != nil {
		pb.CreatedBy = &iam.UserId{Value: *p.CreatedBy}
	}
	pb.DbKind = Database_Kind(Database_Kind_value[p.DbKind])
	pb.DbVersion = p.DbVersion
	pb.IsBuiltin = p.IsBuiltin
	// Source deserialize -> source
	if len(p.Source) > 0 {
		var msg Package_PackageSource
		if err := protojson.Unmarshal(p.Source, &msg); err == nil {
			pb.Source = &msg
		}
	}
	return pb
}
