// Code generated by schemapbgen. DO NOT EDIT.

package providers

import (
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/structpb"

	"github.com/stroppy-io/schemapb/schemapb"
)

var _ = time.Second // keep imports used
var _ = fmt.Sprintf
var _ = sync.Once{}
var _ *schemapb.Schema
var _ *structpb.Struct
var _ = proto.Marshal

// DockerProviderConfig: Local Docker provider settings: agent image, network and host capacity limits.
type DockerProviderConfig struct {
	Image *string `json:"image,omitempty"`
	// Empty = default bridge.
	Network *string `json:"network,omitempty"`
	// Required for systemd PID 1 + cgroup mounts.
	Privileged *bool                        `json:"privileged,omitempty"`
	Dns        []string                     `json:"dns,omitempty"`
	Limits     *DockerProviderConfig_Limits `json:"limits,omitempty"`
}

type DockerProviderConfig_Limits struct {
	// 0 = unlimited.
	MaxContainers *int32 `json:"max_containers,omitempty"`
	MaxCores      *int32 `json:"max_cores,omitempty"`
	MaxMemoryGb   *int32 `json:"max_memory_gb,omitempty"`
	MaxDiskGb     *int32 `json:"max_disk_gb,omitempty"`
}

var _schemaDockerProviderConfigWire = []byte{
	0x0a, 0x19, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x06, 0x64, 0x6f,
	0x63, 0x6b, 0x65, 0x72, 0x1a, 0x05, 0x31, 0x2e, 0x30, 0x2e, 0x30, 0x12, 0x4e, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x20, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x20, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x20, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x3a, 0x20, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x20, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2c, 0x20, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x20, 0x61, 0x6e, 0x64, 0x20, 0x68, 0x6f, 0x73, 0x74, 0x20, 0x63, 0x61, 0x70, 0x61, 0x63,
	0x69, 0x74, 0x79, 0x20, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x2e, 0x1a, 0x2d, 0x0a, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0xba, 0x01, 0x0b, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x20, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x6a, 0x16, 0x0a, 0x14, 0x73, 0x74, 0x72, 0x6f, 0x70, 0x70, 0x79, 0x2d, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x3a, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x0a, 0x07, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x17, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x20, 0x3d, 0x20, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x20, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0xba, 0x01,
	0x0e, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x20, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x6a,
	0x00, 0x1a, 0x4a, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x64, 0x12,
	0x2b, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x20, 0x66, 0x6f, 0x72, 0x20, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x64, 0x20, 0x50, 0x49, 0x44, 0x20, 0x31, 0x20, 0x2b, 0x20, 0x63, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x20, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0xba, 0x01, 0x0a, 0x50,
	0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x64, 0x62, 0x02, 0x08, 0x01, 0x1a, 0x21, 0x0a,
	0x03, 0x64, 0x6e, 0x73, 0xba, 0x01, 0x0b, 0x44, 0x4e, 0x53, 0x20, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x73, 0x8a, 0x01, 0x0b, 0x0a, 0x07, 0x0a, 0x03, 0x64, 0x6e, 0x73, 0x6a, 0x00, 0x18, 0x08,
	0x1a, 0xc6, 0x01, 0x0a, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0xba, 0x01, 0x0b, 0x48, 0x6f,
	0x73, 0x74, 0x20, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x92, 0x01, 0xac, 0x01, 0x0a, 0xa9, 0x01,
	0x1a, 0x37, 0x0a, 0x0e, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x73, 0x12, 0x0e, 0x30, 0x20, 0x3d, 0x20, 0x75, 0x6e, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65,
	0x64, 0x2e, 0xba, 0x01, 0x0e, 0x4d, 0x61, 0x78, 0x20, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x73, 0x42, 0x04, 0x08, 0x00, 0x20, 0x00, 0x1a, 0x1e, 0x0a, 0x09, 0x6d, 0x61, 0x78,
	0x5f, 0x63, 0x6f, 0x72, 0x65, 0x73, 0xba, 0x01, 0x0a, 0x48, 0x6f, 0x73, 0x74, 0x20, 0x63, 0x6f,
	0x72, 0x65, 0x73, 0x42, 0x04, 0x08, 0x00, 0x20, 0x00, 0x1a, 0x28, 0x0a, 0x0d, 0x6d, 0x61, 0x78,
	0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x67, 0x62, 0xb2, 0x01, 0x02, 0x47, 0x42, 0xba,
	0x01, 0x0b, 0x48, 0x6f, 0x73, 0x74, 0x20, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x42, 0x04, 0x08,
	0x00, 0x20, 0x00, 0x1a, 0x24, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x5f,
	0x67, 0x62, 0xb2, 0x01, 0x02, 0x47, 0x42, 0xba, 0x01, 0x09, 0x48, 0x6f, 0x73, 0x74, 0x20, 0x64,
	0x69, 0x73, 0x6b, 0x42, 0x04, 0x08, 0x00, 0x20, 0x00,
}

var (
	_schemaDockerProviderConfigOnce sync.Once
	_schemaDockerProviderConfigVal  *schemapb.Schema
)

func _schemaDockerProviderConfig() *schemapb.Schema {
	_schemaDockerProviderConfigOnce.Do(func() {
		var s schemapb.Schema
		if err := proto.Unmarshal(_schemaDockerProviderConfigWire, &s); err != nil {
			panic(err)
		}
		_schemaDockerProviderConfigVal = &s
	})
	return _schemaDockerProviderConfigVal
}

// Schema returns the schema this type was generated from.
func (c *DockerProviderConfig) Schema() *schemapb.Schema { return _schemaDockerProviderConfig() }

// Validate marshals the value and runs the schemapb engine against it.
func (c *DockerProviderConfig) Validate() []*schemapb.FieldError {
	st, err := c.ToValues()
	if err != nil {
		return []*schemapb.FieldError{schemapb.NewFieldError("", err.Error())}
	}
	return _schemaDockerProviderConfig().ValidateStruct(st)
}

// DockerProviderConfigIdentity is the schema identity this type was generated from.
var DockerProviderConfigIdentity = &schemapb.SchemaIdentity{Namespace: "provider", Name: "docker", Version: "1.0.0"}

// ToValues marshals the value to a protobuf Struct (JSON-bridged).
func (c *DockerProviderConfig) ToValues() (*structpb.Struct, error) {
	j, err := json.Marshal(c)
	if err != nil {
		return nil, err
	}
	st := &structpb.Struct{}
	if err := st.UnmarshalJSON(j); err != nil {
		return nil, err
	}
	return st, nil
}

// FromValuesDockerProviderConfig decodes a protobuf Struct into a new value.
func FromValuesDockerProviderConfig(st *structpb.Struct) (*DockerProviderConfig, error) {
	j, err := st.MarshalJSON()
	if err != nil {
		return nil, err
	}
	var c DockerProviderConfig
	if err := json.Unmarshal(j, &c); err != nil {
		return nil, err
	}
	return &c, nil
}

// ToFilled wraps the value as a schemapb.Filled against this schema.
func (c *DockerProviderConfig) ToFilled() (*schemapb.Filled, error) {
	st, err := c.ToValues()
	if err != nil {
		return nil, err
	}
	return &schemapb.Filled{Schema: &schemapb.SchemaRef{Source: &schemapb.SchemaRef_Schema{Schema: _schemaDockerProviderConfig()}}, Values: st}, nil
}

// ToBaked wraps the value as a schemapb.Baked (embedded schema + values).
func (c *DockerProviderConfig) ToBaked() (*schemapb.Baked, error) {
	st, err := c.ToValues()
	if err != nil {
		return nil, err
	}
	return &schemapb.Baked{Schema: _schemaDockerProviderConfig(), Values: st}, nil
}

func (c *DockerProviderConfig) GetImage() string {
	if c == nil || c.Image == nil {
		var zero string
		return zero
	}
	return *c.Image
}

func (c *DockerProviderConfig) GetNetwork() string {
	if c == nil || c.Network == nil {
		var zero string
		return zero
	}
	return *c.Network
}

func (c *DockerProviderConfig) GetPrivileged() bool {
	if c == nil || c.Privileged == nil {
		var zero bool
		return zero
	}
	return *c.Privileged
}

func (c *DockerProviderConfig) GetDns() []string {
	if c == nil || c.Dns == nil {
		var zero []string
		return zero
	}
	return c.Dns
}

func (c *DockerProviderConfig) GetLimits() DockerProviderConfig_Limits {
	if c == nil || c.Limits == nil {
		var zero DockerProviderConfig_Limits
		return zero
	}
	return *c.Limits
}

// NewDockerProviderConfig returns an empty DockerProviderConfig for chained construction.
func NewDockerProviderConfig() *DockerProviderConfig { return &DockerProviderConfig{} }

func (c *DockerProviderConfig) WithImage(v string) *DockerProviderConfig { c.Image = &v; return c }

func (c *DockerProviderConfig) WithNetwork(v string) *DockerProviderConfig { c.Network = &v; return c }

func (c *DockerProviderConfig) WithPrivileged(v bool) *DockerProviderConfig {
	c.Privileged = &v
	return c
}

func (c *DockerProviderConfig) WithDns(v []string) *DockerProviderConfig { c.Dns = v; return c }

func (c *DockerProviderConfig) WithLimits(v DockerProviderConfig_Limits) *DockerProviderConfig {
	c.Limits = &v
	return c
}

// Clone deep-copies the value via its JSON representation.
func (c *DockerProviderConfig) Clone() *DockerProviderConfig {
	if c == nil {
		return nil
	}
	j, _ := json.Marshal(c)
	var out DockerProviderConfig
	_ = json.Unmarshal(j, &out)
	return &out
}

func (c *DockerProviderConfig_Limits) GetMaxContainers() int32 {
	if c == nil || c.MaxContainers == nil {
		var zero int32
		return zero
	}
	return *c.MaxContainers
}

func (c *DockerProviderConfig_Limits) GetMaxCores() int32 {
	if c == nil || c.MaxCores == nil {
		var zero int32
		return zero
	}
	return *c.MaxCores
}

func (c *DockerProviderConfig_Limits) GetMaxMemoryGb() int32 {
	if c == nil || c.MaxMemoryGb == nil {
		var zero int32
		return zero
	}
	return *c.MaxMemoryGb
}

func (c *DockerProviderConfig_Limits) GetMaxDiskGb() int32 {
	if c == nil || c.MaxDiskGb == nil {
		var zero int32
		return zero
	}
	return *c.MaxDiskGb
}

// NewDockerProviderConfig_Limits returns an empty DockerProviderConfig_Limits for chained construction.
func NewDockerProviderConfig_Limits() *DockerProviderConfig_Limits {
	return &DockerProviderConfig_Limits{}
}

func (c *DockerProviderConfig_Limits) WithMaxContainers(v int32) *DockerProviderConfig_Limits {
	c.MaxContainers = &v
	return c
}

func (c *DockerProviderConfig_Limits) WithMaxCores(v int32) *DockerProviderConfig_Limits {
	c.MaxCores = &v
	return c
}

func (c *DockerProviderConfig_Limits) WithMaxMemoryGb(v int32) *DockerProviderConfig_Limits {
	c.MaxMemoryGb = &v
	return c
}

func (c *DockerProviderConfig_Limits) WithMaxDiskGb(v int32) *DockerProviderConfig_Limits {
	c.MaxDiskGb = &v
	return c
}

// Clone deep-copies the value via its JSON representation.
func (c *DockerProviderConfig_Limits) Clone() *DockerProviderConfig_Limits {
	if c == nil {
		return nil
	}
	j, _ := json.Marshal(c)
	var out DockerProviderConfig_Limits
	_ = json.Unmarshal(j, &out)
	return &out
}

// DefaultDockerProviderConfig returns a new value with schema defaults applied.
func DefaultDockerProviderConfig() *DockerProviderConfig {
	c := &DockerProviderConfig{}
	c.Default()
	return c
}

// Default fills schema default values into empty fields of c.
func (c *DockerProviderConfig) Default() {
	st, err := c.ToValues()
	if err != nil {
		return
	}
	m := st.AsMap()
	_schemaDockerProviderConfig().ApplyDefaults(m)
	ns, err := structpb.NewStruct(m)
	if err != nil {
		return
	}
	if got, err := FromValuesDockerProviderConfig(ns); err == nil {
		*c = *got
	}
}
