// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: stroppy/test.proto

package stroppy

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	deployment "github.com/stroppy-io/hatchet-workflow/internal/proto/deployment"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = deployment.Target(0)
)

// Validate checks the field values on StroppyCli with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StroppyCli) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StroppyCli with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StroppyCliMultiError, or
// nil if none found.
func (m *StroppyCli) ValidateAll() error {
	return m.validate(true)
}

func (m *StroppyCli) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetVersion()) < 1 {
		err := StroppyCliValidationError{
			field:  "Version",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := StroppyCli_Workload_name[int32(m.GetWorkload())]; !ok {
		err := StroppyCliValidationError{
			field:  "Workload",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for StroppyEnv

	if m.BinaryPath != nil {
		// no validation rules for BinaryPath
	}

	if m.Workdir != nil {
		// no validation rules for Workdir
	}

	if len(errors) > 0 {
		return StroppyCliMultiError(errors)
	}

	return nil
}

// StroppyCliMultiError is an error wrapping multiple validation errors
// returned by StroppyCli.ValidateAll() if the designated constraints aren't met.
type StroppyCliMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StroppyCliMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StroppyCliMultiError) AllErrors() []error { return m }

// StroppyCliValidationError is the validation error returned by
// StroppyCli.Validate if the designated constraints aren't met.
type StroppyCliValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StroppyCliValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StroppyCliValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StroppyCliValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StroppyCliValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StroppyCliValidationError) ErrorName() string { return "StroppyCliValidationError" }

// Error satisfies the builtin error interface
func (e StroppyCliValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStroppyCli.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StroppyCliValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StroppyCliValidationError{}

// Validate checks the field values on Test with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Test) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Test with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in TestMultiError, or nil if none found.
func (m *Test) ValidateAll() error {
	return m.validate(true)
}

func (m *Test) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if m.GetStroppyCli() == nil {
		err := TestValidationError{
			field:  "StroppyCli",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetStroppyCli()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TestValidationError{
					field:  "StroppyCli",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TestValidationError{
					field:  "StroppyCli",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStroppyCli()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TestValidationError{
				field:  "StroppyCli",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetStroppyHardware() == nil {
		err := TestValidationError{
			field:  "StroppyHardware",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetStroppyHardware()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TestValidationError{
					field:  "StroppyHardware",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TestValidationError{
					field:  "StroppyHardware",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStroppyHardware()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TestValidationError{
				field:  "StroppyHardware",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	switch v := m.DatabaseRef.(type) {
	case *Test_DatabaseTemplate:
		if v == nil {
			err := TestValidationError{
				field:  "DatabaseRef",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetDatabaseTemplate()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TestValidationError{
						field:  "DatabaseTemplate",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TestValidationError{
						field:  "DatabaseTemplate",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDatabaseTemplate()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TestValidationError{
					field:  "DatabaseTemplate",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *Test_ConnectionString:
		if v == nil {
			err := TestValidationError{
				field:  "DatabaseRef",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if utf8.RuneCountInString(m.GetConnectionString()) < 1 {
			err := TestValidationError{
				field:  "ConnectionString",
				reason: "value length must be at least 1 runes",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	default:
		_ = v // ensures v is used
	}

	if m.Description != nil {
		// no validation rules for Description
	}

	if len(errors) > 0 {
		return TestMultiError(errors)
	}

	return nil
}

// TestMultiError is an error wrapping multiple validation errors returned by
// Test.ValidateAll() if the designated constraints aren't met.
type TestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TestMultiError) AllErrors() []error { return m }

// TestValidationError is the validation error returned by Test.Validate if the
// designated constraints aren't met.
type TestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TestValidationError) ErrorName() string { return "TestValidationError" }

// Error satisfies the builtin error interface
func (e TestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TestValidationError{}

// Validate checks the field values on TestResult with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TestResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TestResult with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TestResultMultiError, or
// nil if none found.
func (m *TestResult) ValidateAll() error {
	return m.validate(true)
}

func (m *TestResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RunId

	if m.GetTest() == nil {
		err := TestResultValidationError{
			field:  "Test",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTest()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TestResultValidationError{
					field:  "Test",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TestResultValidationError{
					field:  "Test",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTest()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TestResultValidationError{
				field:  "Test",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GrafanaUrl != nil {
		// no validation rules for GrafanaUrl
	}

	if len(errors) > 0 {
		return TestResultMultiError(errors)
	}

	return nil
}

// TestResultMultiError is an error wrapping multiple validation errors
// returned by TestResult.ValidateAll() if the designated constraints aren't met.
type TestResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TestResultMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TestResultMultiError) AllErrors() []error { return m }

// TestResultValidationError is the validation error returned by
// TestResult.Validate if the designated constraints aren't met.
type TestResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TestResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TestResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TestResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TestResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TestResultValidationError) ErrorName() string { return "TestResultValidationError" }

// Error satisfies the builtin error interface
func (e TestResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTestResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TestResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TestResultValidationError{}

// Validate checks the field values on TestSuite with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TestSuite) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TestSuite with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TestSuiteMultiError, or nil
// if none found.
func (m *TestSuite) ValidateAll() error {
	return m.validate(true)
}

func (m *TestSuite) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTests() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TestSuiteValidationError{
						field:  fmt.Sprintf("Tests[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TestSuiteValidationError{
						field:  fmt.Sprintf("Tests[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TestSuiteValidationError{
					field:  fmt.Sprintf("Tests[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return TestSuiteMultiError(errors)
	}

	return nil
}

// TestSuiteMultiError is an error wrapping multiple validation errors returned
// by TestSuite.ValidateAll() if the designated constraints aren't met.
type TestSuiteMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TestSuiteMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TestSuiteMultiError) AllErrors() []error { return m }

// TestSuiteValidationError is the validation error returned by
// TestSuite.Validate if the designated constraints aren't met.
type TestSuiteValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TestSuiteValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TestSuiteValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TestSuiteValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TestSuiteValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TestSuiteValidationError) ErrorName() string { return "TestSuiteValidationError" }

// Error satisfies the builtin error interface
func (e TestSuiteValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTestSuite.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TestSuiteValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TestSuiteValidationError{}

// Validate checks the field values on TestSuiteResult with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TestSuiteResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TestSuiteResult with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TestSuiteResultMultiError, or nil if none found.
func (m *TestSuiteResult) ValidateAll() error {
	return m.validate(true)
}

func (m *TestSuiteResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetSuite() == nil {
		err := TestSuiteResultValidationError{
			field:  "Suite",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetSuite()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TestSuiteResultValidationError{
					field:  "Suite",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TestSuiteResultValidationError{
					field:  "Suite",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSuite()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TestSuiteResultValidationError{
				field:  "Suite",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(m.GetResults()) < 1 {
		err := TestSuiteResultValidationError{
			field:  "Results",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetResults() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TestSuiteResultValidationError{
						field:  fmt.Sprintf("Results[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TestSuiteResultValidationError{
						field:  fmt.Sprintf("Results[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TestSuiteResultValidationError{
					field:  fmt.Sprintf("Results[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return TestSuiteResultMultiError(errors)
	}

	return nil
}

// TestSuiteResultMultiError is an error wrapping multiple validation errors
// returned by TestSuiteResult.ValidateAll() if the designated constraints
// aren't met.
type TestSuiteResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TestSuiteResultMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TestSuiteResultMultiError) AllErrors() []error { return m }

// TestSuiteResultValidationError is the validation error returned by
// TestSuiteResult.Validate if the designated constraints aren't met.
type TestSuiteResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TestSuiteResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TestSuiteResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TestSuiteResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TestSuiteResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TestSuiteResultValidationError) ErrorName() string { return "TestSuiteResultValidationError" }

// Error satisfies the builtin error interface
func (e TestSuiteResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTestSuiteResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TestSuiteResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TestSuiteResultValidationError{}

// Validate checks the field values on RunSettings with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RunSettings) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RunSettings with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RunSettingsMultiError, or
// nil if none found.
func (m *RunSettings) ValidateAll() error {
	return m.validate(true)
}

func (m *RunSettings) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetRunId()) < 1 {
		err := RunSettingsValidationError{
			field:  "RunId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := deployment.Target_name[int32(m.GetTarget())]; !ok {
		err := RunSettingsValidationError{
			field:  "Target",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetSettings() == nil {
		err := RunSettingsValidationError{
			field:  "Settings",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetSettings()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RunSettingsValidationError{
					field:  "Settings",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RunSettingsValidationError{
					field:  "Settings",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSettings()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RunSettingsValidationError{
				field:  "Settings",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetTest() == nil {
		err := RunSettingsValidationError{
			field:  "Test",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTest()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RunSettingsValidationError{
					field:  "Test",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RunSettingsValidationError{
					field:  "Test",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTest()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RunSettingsValidationError{
				field:  "Test",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RunSettingsMultiError(errors)
	}

	return nil
}

// RunSettingsMultiError is an error wrapping multiple validation errors
// returned by RunSettings.ValidateAll() if the designated constraints aren't met.
type RunSettingsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RunSettingsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RunSettingsMultiError) AllErrors() []error { return m }

// RunSettingsValidationError is the validation error returned by
// RunSettings.Validate if the designated constraints aren't met.
type RunSettingsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RunSettingsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RunSettingsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RunSettingsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RunSettingsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RunSettingsValidationError) ErrorName() string { return "RunSettingsValidationError" }

// Error satisfies the builtin error interface
func (e RunSettingsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRunSettings.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RunSettingsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RunSettingsValidationError{}
