version: "1"
engine: postgresql
options:
  defaultSchema: public
schema:
  - file: internal/infrastructure/postgres/schema.sql
queries:
  - dir: internal/infrastructure/postgres/queries
migrations:
  - dir: internal/infrastructure/postgres/migrations
plugins:
  - name: go
    binary: ./bin/sqld-gen-go
    out: internal/infrastructure/postgres/gen/db
    options:
      package: db
      nullMode: pointer
  - name: bob
    binary: ./bin/sqld-gen-bob
    out: internal/infrastructure/postgres/gen/bob
    options:
      package: models
      typesPackage: github.com/stroppy-io/stroppy-cloud/internal/infrastructure/postgres/gen/db
      nullMode: pointer
