syntax = "proto3";

package cloud.v1.deployment;

import "cloud/v1/deployment/deployment.proto";
import "validate/validate.proto";

option go_package = "github.com/stroppy-io/stroppy-cloud/internal/proto/cloud/v1/deployment";

message QuotaRequest {
    deployment.Provider provider = 1 [(validate.rules).enum = {defined_only: true, not_in: [0]}];
    string quota_name = 2 [(validate.rules).string = {min_len: 1, max_len: 128}];
    uint64 requested = 3 [(validate.rules).uint64 = {gte: 1}];
}

message Quota {
    deployment.Provider provider = 1 [(validate.rules).enum = {defined_only: true, not_in: [0]}];
    // TODO: Convert to enum by providers
    string quota_name = 2 [(validate.rules).string = {min_len: 1, max_len: 128}];
    uint64 limit = 3 [(validate.rules).uint64 = {gte: 1}];
    uint64 used = 4 [(validate.rules).uint64 = {gte: 0}];
    uint64 available = 5 [(validate.rules).uint64 = {gte: 0}];
}