// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts,import_extension=ts"
// @generated from file cloud/v1/testing/test_suite_run.proto (package cloud.v1.testing, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MetricSeriesList, TestSuiteRunId } from "./test_run_pbts";
import { GetTestSuiteRunMetricsRequest, GetTestSuiteRunResponse, StreamTestSuiteRunLogsRequest, TestSuiteRun, TestSuiteRun_List, TestSuiteRunProgress, WatchTestSuiteRunRequest } from "./test_suite_run_pbts";
import { MethodIdempotency, MethodKind } from "@bufbuild/protobuf";
import { TestSuiteId } from "./test_suite_pbts";
import { TenantId } from "../iam/tenant_pbts";
import { LogLine } from "../agent/protocol_pbts";

/**
 * @generated from service cloud.v1.testing.TestSuiteRunService
 */
export const TestSuiteRunService = {
  typeName: "cloud.v1.testing.TestSuiteRunService",
  methods: {
    /**
     * GetTestSuiteRun — returns suite run plus meta-DAG progress and per-child TestRun projections. 
     *
     * @generated from rpc cloud.v1.testing.TestSuiteRunService.GetTestSuiteRun
     */
    getTestSuiteRun: {
      name: "GetTestSuiteRun",
      I: TestSuiteRunId,
      O: GetTestSuiteRunResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * @generated from rpc cloud.v1.testing.TestSuiteRunService.ListBySuite
     */
    listBySuite: {
      name: "ListBySuite",
      I: TestSuiteId,
      O: TestSuiteRun_List,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * @generated from rpc cloud.v1.testing.TestSuiteRunService.ListByTenant
     */
    listByTenant: {
      name: "ListByTenant",
      I: TenantId,
      O: TestSuiteRun_List,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * WatchTestSuiteRun — server-streams progress snapshots as suite/children DAG state changes. 
     *
     * @generated from rpc cloud.v1.testing.TestSuiteRunService.WatchTestSuiteRun
     */
    watchTestSuiteRun: {
      name: "WatchTestSuiteRun",
      I: WatchTestSuiteRunRequest,
      O: TestSuiteRunProgress,
      kind: MethodKind.ServerStreaming,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * StreamTestSuiteRunLogs — aggregated log feed across child TestRuns. 
     *
     * @generated from rpc cloud.v1.testing.TestSuiteRunService.StreamTestSuiteRunLogs
     */
    streamTestSuiteRunLogs: {
      name: "StreamTestSuiteRunLogs",
      I: StreamTestSuiteRunLogsRequest,
      O: LogLine,
      kind: MethodKind.ServerStreaming,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * GetTestSuiteRunMetrics — aggregated metrics across child TestRuns. 
     *
     * @generated from rpc cloud.v1.testing.TestSuiteRunService.GetTestSuiteRunMetrics
     */
    getTestSuiteRunMetrics: {
      name: "GetTestSuiteRunMetrics",
      I: GetTestSuiteRunMetricsRequest,
      O: MetricSeriesList,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * @generated from rpc cloud.v1.testing.TestSuiteRunService.CancelTestSuiteRun
     */
    cancelTestSuiteRun: {
      name: "CancelTestSuiteRun",
      I: TestSuiteRunId,
      O: TestSuiteRun,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.Idempotent,
    },
    /**
     * LaunchTestSuite — produces a TestSuiteRun with materialized matrix cells. 
     *
     * @generated from rpc cloud.v1.testing.TestSuiteRunService.LaunchTestSuite
     */
    launchTestSuite: {
      name: "LaunchTestSuite",
      I: TestSuiteId,
      O: TestSuiteRun,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.Idempotent,
    },
  }
} as const;

