// Code generated by protoc-gen-ogen. DO NOT EDIT.

package api

import (
	convert "github.com/gopherex/protoc-gen-go-ogen/convert"
	rest "github.com/stroppy-io/stroppy-cloud/internal/proto/cloud/v1/api/rest"
	dsl "github.com/stroppy-io/stroppy-cloud/internal/proto/cloud/v1/dsl"
	models "github.com/stroppy-io/stroppy-cloud/internal/proto/cloud/v1/models"
)

// ToOgen converts CheckRecipeRequest to its ogen representation.
func (src *CheckRecipeRequest) ToOgen() (*rest.CheckRecipeRequest, error) {
	var dst rest.CheckRecipeRequest
	if src == nil {
		return &dst, nil
	}
	dst.TenantId.SetTo(string(src.GetTenantId()))
	dst.ID.SetTo(string(src.GetId()))
	return &dst, nil
}

// CheckRecipeRequestFromOgen converts the ogen representation back to CheckRecipeRequest.
func CheckRecipeRequestFromOgen(src *rest.CheckRecipeRequest) (*CheckRecipeRequest, error) {
	if src == nil {
		return nil, nil
	}
	dst := &CheckRecipeRequest{}
	if v1, ok := src.TenantId.Get(); ok {
		dst.TenantId = string(v1)
	}
	if v2, ok := src.ID.Get(); ok {
		dst.Id = string(v2)
	}
	return dst, nil
}

// ToOgen converts CheckRecipeResponse to its ogen representation.
func (src *CheckRecipeResponse) ToOgen() (*rest.CheckRecipeResponse, error) {
	var dst rest.CheckRecipeResponse
	if src == nil {
		return &dst, nil
	}
	c1, err := convert.SliceErr(src.GetDiagnostics(), func(e *dsl.Diagnostic) (zero rest.Diagnostic, _ error) {
		o2, err := DiagnosticToOgen(e)
		if err != nil {
			return zero, err
		}
		return *o2, nil
	})
	if err != nil {
		return nil, err
	}
	dst.Diagnostics = c1
	return &dst, nil
}

// CheckRecipeResponseFromOgen converts the ogen representation back to CheckRecipeResponse.
func CheckRecipeResponseFromOgen(src *rest.CheckRecipeResponse) (*CheckRecipeResponse, error) {
	if src == nil {
		return nil, nil
	}
	dst := &CheckRecipeResponse{}
	c1, err := convert.SliceErr(src.Diagnostics, func(e rest.Diagnostic) (zero *dsl.Diagnostic, _ error) {
		m2, err := DiagnosticFromOgen(&e)
		if err != nil {
			return zero, err
		}
		return m2, nil
	})
	if err != nil {
		return nil, err
	}
	dst.Diagnostics = c1
	return dst, nil
}

// ToOgen converts CreateRecipeRequest to its ogen representation.
func (src *CreateRecipeRequest) ToOgen() (*rest.CreateRecipeRequest, error) {
	var dst rest.CreateRecipeRequest
	if src == nil {
		return &dst, nil
	}
	dst.TenantId.SetTo(string(src.GetTenantId()))
	o1, err := RecipeRecordToOgen(src.GetRecipe())
	if err != nil {
		return nil, err
	}
	dst.Recipe = *o1
	return &dst, nil
}

// CreateRecipeRequestFromOgen converts the ogen representation back to CreateRecipeRequest.
func CreateRecipeRequestFromOgen(src *rest.CreateRecipeRequest) (*CreateRecipeRequest, error) {
	if src == nil {
		return nil, nil
	}
	dst := &CreateRecipeRequest{}
	if v1, ok := src.TenantId.Get(); ok {
		dst.TenantId = string(v1)
	}
	m2, err := RecipeRecordFromOgen(&src.Recipe)
	if err != nil {
		return nil, err
	}
	dst.Recipe = m2
	return dst, nil
}

// ToOgen converts CreateRecipeResponse to its ogen representation.
func (src *CreateRecipeResponse) ToOgen() (*rest.CreateRecipeResponse, error) {
	var dst rest.CreateRecipeResponse
	if src == nil {
		return &dst, nil
	}
	o1, err := RecipeRecordToOgen(src.GetRecipe())
	if err != nil {
		return nil, err
	}
	dst.Recipe = *o1
	return &dst, nil
}

// CreateRecipeResponseFromOgen converts the ogen representation back to CreateRecipeResponse.
func CreateRecipeResponseFromOgen(src *rest.CreateRecipeResponse) (*CreateRecipeResponse, error) {
	if src == nil {
		return nil, nil
	}
	dst := &CreateRecipeResponse{}
	m1, err := RecipeRecordFromOgen(&src.Recipe)
	if err != nil {
		return nil, err
	}
	dst.Recipe = m1
	return dst, nil
}

// ToOgen converts DeleteRecipeRequest to its ogen representation.
func (src *DeleteRecipeRequest) ToOgen() (*rest.DeleteRecipeRequest, error) {
	var dst rest.DeleteRecipeRequest
	if src == nil {
		return &dst, nil
	}
	dst.TenantId.SetTo(string(src.GetTenantId()))
	dst.ID.SetTo(string(src.GetId()))
	return &dst, nil
}

// DeleteRecipeRequestFromOgen converts the ogen representation back to DeleteRecipeRequest.
func DeleteRecipeRequestFromOgen(src *rest.DeleteRecipeRequest) (*DeleteRecipeRequest, error) {
	if src == nil {
		return nil, nil
	}
	dst := &DeleteRecipeRequest{}
	if v1, ok := src.TenantId.Get(); ok {
		dst.TenantId = string(v1)
	}
	if v2, ok := src.ID.Get(); ok {
		dst.Id = string(v2)
	}
	return dst, nil
}

// ToOgen converts DeleteRecipeResponse to its ogen representation.
func (src *DeleteRecipeResponse) ToOgen() (*rest.DeleteRecipeResponse, error) {
	var dst rest.DeleteRecipeResponse
	if src == nil {
		return &dst, nil
	}
	return &dst, nil
}

// DeleteRecipeResponseFromOgen converts the ogen representation back to DeleteRecipeResponse.
func DeleteRecipeResponseFromOgen(src *rest.DeleteRecipeResponse) (*DeleteRecipeResponse, error) {
	if src == nil {
		return nil, nil
	}
	dst := &DeleteRecipeResponse{}
	return dst, nil
}

// ToOgen converts GetRecipeRequest to its ogen representation.
func (src *GetRecipeRequest) ToOgen() (*rest.GetRecipeRequest, error) {
	var dst rest.GetRecipeRequest
	if src == nil {
		return &dst, nil
	}
	dst.TenantId.SetTo(string(src.GetTenantId()))
	dst.ID.SetTo(string(src.GetId()))
	return &dst, nil
}

// GetRecipeRequestFromOgen converts the ogen representation back to GetRecipeRequest.
func GetRecipeRequestFromOgen(src *rest.GetRecipeRequest) (*GetRecipeRequest, error) {
	if src == nil {
		return nil, nil
	}
	dst := &GetRecipeRequest{}
	if v1, ok := src.TenantId.Get(); ok {
		dst.TenantId = string(v1)
	}
	if v2, ok := src.ID.Get(); ok {
		dst.Id = string(v2)
	}
	return dst, nil
}

// ToOgen converts GetRecipeResponse to its ogen representation.
func (src *GetRecipeResponse) ToOgen() (*rest.GetRecipeResponse, error) {
	var dst rest.GetRecipeResponse
	if src == nil {
		return &dst, nil
	}
	o1, err := RecipeRecordToOgen(src.GetRecipe())
	if err != nil {
		return nil, err
	}
	dst.Recipe = *o1
	return &dst, nil
}

// GetRecipeResponseFromOgen converts the ogen representation back to GetRecipeResponse.
func GetRecipeResponseFromOgen(src *rest.GetRecipeResponse) (*GetRecipeResponse, error) {
	if src == nil {
		return nil, nil
	}
	dst := &GetRecipeResponse{}
	m1, err := RecipeRecordFromOgen(&src.Recipe)
	if err != nil {
		return nil, err
	}
	dst.Recipe = m1
	return dst, nil
}

// ToOgen converts ListRecipesRequest to its ogen representation.
func (src *ListRecipesRequest) ToOgen() (*rest.ListRecipesRequest, error) {
	var dst rest.ListRecipesRequest
	if src == nil {
		return &dst, nil
	}
	dst.TenantId.SetTo(string(src.GetTenantId()))
	if src.Filter != nil {
		o1, err := EntityFilterToOgen(src.GetFilter())
		if err != nil {
			return nil, err
		}
		dst.Filter.SetTo(*o1)
	}
	if src.Page != nil {
		o2, err := PageToOgen(src.GetPage())
		if err != nil {
			return nil, err
		}
		dst.Page.SetTo(*o2)
	}
	return &dst, nil
}

// ListRecipesRequestFromOgen converts the ogen representation back to ListRecipesRequest.
func ListRecipesRequestFromOgen(src *rest.ListRecipesRequest) (*ListRecipesRequest, error) {
	if src == nil {
		return nil, nil
	}
	dst := &ListRecipesRequest{}
	if v1, ok := src.TenantId.Get(); ok {
		dst.TenantId = string(v1)
	}
	if v2, ok := src.Filter.Get(); ok {
		m3, err := EntityFilterFromOgen(&v2)
		if err != nil {
			return nil, err
		}
		dst.Filter = m3
	}
	if v4, ok := src.Page.Get(); ok {
		m5, err := PageFromOgen(&v4)
		if err != nil {
			return nil, err
		}
		dst.Page = m5
	}
	return dst, nil
}

// ToOgen converts ListRecipesResponse to its ogen representation.
func (src *ListRecipesResponse) ToOgen() (*rest.ListRecipesResponse, error) {
	var dst rest.ListRecipesResponse
	if src == nil {
		return &dst, nil
	}
	c1, err := convert.SliceErr(src.GetRecipes(), func(e *models.RecipeRecord) (zero rest.RecipeRecord, _ error) {
		o2, err := RecipeRecordToOgen(e)
		if err != nil {
			return zero, err
		}
		return *o2, nil
	})
	if err != nil {
		return nil, err
	}
	dst.Recipes = c1
	dst.NextPageToken.SetTo(string(src.GetNextPageToken()))
	return &dst, nil
}

// ListRecipesResponseFromOgen converts the ogen representation back to ListRecipesResponse.
func ListRecipesResponseFromOgen(src *rest.ListRecipesResponse) (*ListRecipesResponse, error) {
	if src == nil {
		return nil, nil
	}
	dst := &ListRecipesResponse{}
	c1, err := convert.SliceErr(src.Recipes, func(e rest.RecipeRecord) (zero *models.RecipeRecord, _ error) {
		m2, err := RecipeRecordFromOgen(&e)
		if err != nil {
			return zero, err
		}
		return m2, nil
	})
	if err != nil {
		return nil, err
	}
	dst.Recipes = c1
	if v3, ok := src.NextPageToken.Get(); ok {
		dst.NextPageToken = string(v3)
	}
	return dst, nil
}
