syntax = "proto3";

package cloud.v1.api.admin;

import "cloud/v1/models/settings.proto";
import "google/protobuf/empty.proto";
import "validate/validate.proto";

option go_package = "github.com/stroppy-io/stroppy-cloud/internal/proto/cloud/v1/api/admin";

message UpdateSettingsItemRequest {
    models.SettingsItemId settings_item_id = 1 [(validate.rules).message.required = true];
    models.SettingsItem.Value value = 2 [(validate.rules).message.required = true];
}
message ListSettingsItemsRequest {}

service SettingsService {
    rpc ListSettingsItems (ListSettingsItemsRequest) returns (models.SettingsItem.List) {option idempotency_level = NO_SIDE_EFFECTS;};
    rpc GetSettingsItem (models.SettingsItemId) returns (models.SettingsItem) {option idempotency_level = NO_SIDE_EFFECTS;};
    rpc UpdateSettingsItem (UpdateSettingsItemRequest) returns (models.SettingsItem) {option idempotency_level = IDEMPOTENT;};
}