// Code generated by protoc-gen-go_temporal. DO NOT EDIT.
// versions:
//
//	protoc-gen-go_temporal dev (latest)
//	protoc major:0  minor:14  patch:1  suffix:"v0.16.6-bufbuild-protocompile-easyp"
//
// source: cloud/v1/workflow/test.proto
package workflow

import (
	"context"
	"errors"
	"fmt"
	helpers "github.com/cludden/protoc-gen-go-temporal/pkg/helpers"
	scheme "github.com/cludden/protoc-gen-go-temporal/pkg/scheme"
	enumsv1 "go.temporal.io/api/enums/v1"
	client "go.temporal.io/sdk/client"
	converter "go.temporal.io/sdk/converter"
	temporal "go.temporal.io/sdk/temporal"
	testsuite "go.temporal.io/sdk/testsuite"
	worker "go.temporal.io/sdk/worker"
	workflow "go.temporal.io/sdk/workflow"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	"log/slog"
	"sync"
	"sync/atomic"
	"time"
)

// TestServiceTaskQueue is the default task-queue for a cloud.v1.workflow.TestService worker
var TestServiceTaskQueue = "stroppy-cloud"

// cloud.v1.workflow.TestService workflow names
const (
	PlaceholderWorkflowWorkflowName = "PlaceholderWorkflow"
)

// cloud.v1.workflow.TestService query names
const (
	GetRunStateQueryName = "GetRunState"
)

// cloud.v1.workflow.TestService signal names
const (
	UpdateStageSignalName = "UpdateStage"
)

// TestServiceClient describes a client for a(n) cloud.v1.workflow.TestService worker
type TestServiceClient interface {
	// PlaceholderWorkflow: see the message doc above — required by the
	// code generator, never started.
	PlaceholderWorkflow(ctx context.Context, req *PlaceholderWorkflowRequest, opts ...*PlaceholderWorkflowOptions) (*PlaceholderWorkflowResponse, error)

	// PlaceholderWorkflowAsync starts a(n) PlaceholderWorkflow workflow and returns a handle to the workflow run
	PlaceholderWorkflowAsync(ctx context.Context, req *PlaceholderWorkflowRequest, opts ...*PlaceholderWorkflowOptions) (PlaceholderWorkflowRun, error)

	// GetPlaceholderWorkflow retrieves a handle to an existing PlaceholderWorkflow workflow execution
	GetPlaceholderWorkflow(ctx context.Context, workflowID string, runID string) PlaceholderWorkflowRun

	// CancelWorkflow requests cancellation of an existing workflow execution
	CancelWorkflow(ctx context.Context, workflowID string, runID string) error

	// TerminateWorkflow an existing workflow execution
	TerminateWorkflow(ctx context.Context, workflowID string, runID string, reason string, details ...interface{}) error

	// GetRunState is a Temporal query against a running TestWorkflow returning
	// the live RunState (overall status + per-stage breakdown) for the run
	// Overview. Read-only; takes no input.
	GetRunState(ctx context.Context, workflowID string, runID string) (*RunState, error)

	// UpdateStage is a Temporal signal used by child workflows to update one
	// concrete runtime stage inside the parent TestWorkflow RunState.
	UpdateStage(ctx context.Context, workflowID string, runID string, signal *StageUpdate) error
}

// testServiceClient implements a temporal client for a cloud.v1.workflow.TestService service
type testServiceClient struct {
	client client.Client
	log    *slog.Logger
}

// NewTestServiceClient initializes a new cloud.v1.workflow.TestService client
func NewTestServiceClient(c client.Client, options ...*testServiceClientOptions) TestServiceClient {
	var cfg *testServiceClientOptions
	if len(options) > 0 {
		cfg = options[0]
	} else {
		cfg = NewTestServiceClientOptions()
	}
	return &testServiceClient{
		client: c,
		log:    cfg.getLogger(),
	}
}

// NewTestServiceClientWithOptions initializes a new TestService client with the given options
func NewTestServiceClientWithOptions(c client.Client, opts client.Options, options ...*testServiceClientOptions) (TestServiceClient, error) {
	var err error
	c, err = client.NewClientFromExisting(c, opts)
	if err != nil {
		return nil, fmt.Errorf("error initializing client with options: %w", err)
	}
	var cfg *testServiceClientOptions
	if len(options) > 0 {
		cfg = options[0]
	} else {
		cfg = NewTestServiceClientOptions()
	}
	return &testServiceClient{
		client: c,
		log:    cfg.getLogger(),
	}, nil
}

// testServiceClientOptions describes optional runtime configuration for a TestServiceClient
type testServiceClientOptions struct {
	log *slog.Logger
}

// NewTestServiceClientOptions initializes a new testServiceClientOptions value
func NewTestServiceClientOptions() *testServiceClientOptions {
	return &testServiceClientOptions{}
}

// WithLogger can be used to override the default logger
func (opts *testServiceClientOptions) WithLogger(l *slog.Logger) *testServiceClientOptions {
	if l != nil {
		opts.log = l
	}
	return opts
}

// getLogger returns the configured logger, or the default logger
func (opts *testServiceClientOptions) getLogger() *slog.Logger {
	if opts != nil && opts.log != nil {
		return opts.log
	}
	return slog.Default()
}

// PlaceholderWorkflow: see the message doc above — required by the
// code generator, never started.
func (c *testServiceClient) PlaceholderWorkflow(ctx context.Context, req *PlaceholderWorkflowRequest, options ...*PlaceholderWorkflowOptions) (*PlaceholderWorkflowResponse, error) {
	run, err := c.PlaceholderWorkflowAsync(ctx, req, options...)
	if err != nil {
		return nil, err
	}
	return run.Get(ctx)
}

// PlaceholderWorkflow: see the message doc above — required by the
// code generator, never started.
func (c *testServiceClient) PlaceholderWorkflowAsync(ctx context.Context, req *PlaceholderWorkflowRequest, options ...*PlaceholderWorkflowOptions) (PlaceholderWorkflowRun, error) {
	var o *PlaceholderWorkflowOptions
	if len(options) > 0 && options[0] != nil {
		o = options[0]
	} else {
		o = NewPlaceholderWorkflowOptions()
	}
	opts, err := o.Build(req.ProtoReflect())
	if err != nil {
		return nil, fmt.Errorf("error initializing client.StartWorkflowOptions: %w", err)
	}
	run, err := c.client.ExecuteWorkflow(ctx, opts, PlaceholderWorkflowWorkflowName, req)
	if err != nil {
		return nil, err
	}
	if run == nil {
		return nil, errors.New("execute workflow returned nil run")
	}
	return &placeholderWorkflowRun{
		client: c,
		run:    run,
	}, nil
}

// GetPlaceholderWorkflow fetches an existing PlaceholderWorkflow execution
func (c *testServiceClient) GetPlaceholderWorkflow(ctx context.Context, workflowID string, runID string) PlaceholderWorkflowRun {
	return &placeholderWorkflowRun{
		client: c,
		run:    c.client.GetWorkflow(ctx, workflowID, runID),
	}
}

// CancelWorkflow requests cancellation of an existing workflow execution
func (c *testServiceClient) CancelWorkflow(ctx context.Context, workflowID string, runID string) error {
	return c.client.CancelWorkflow(ctx, workflowID, runID)
}

// TerminateWorkflow terminates an existing workflow execution
func (c *testServiceClient) TerminateWorkflow(ctx context.Context, workflowID string, runID string, reason string, details ...interface{}) error {
	return c.client.TerminateWorkflow(ctx, workflowID, runID, reason, details...)
}

// GetRunState is a Temporal query against a running TestWorkflow returning
// the live RunState (overall status + per-stage breakdown) for the run
// Overview. Read-only; takes no input.
func (c *testServiceClient) GetRunState(ctx context.Context, workflowID string, runID string) (*RunState, error) {
	var resp RunState
	if val, err := c.client.QueryWorkflow(ctx, workflowID, runID, GetRunStateQueryName); err != nil {
		return nil, err
	} else if err = val.Get(&resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateStage is a Temporal signal used by child workflows to update one
// concrete runtime stage inside the parent TestWorkflow RunState.
func (c *testServiceClient) UpdateStage(ctx context.Context, workflowID string, runID string, signal *StageUpdate) error {
	return c.client.SignalWorkflow(ctx, workflowID, runID, UpdateStageSignalName, signal)
}

// PlaceholderWorkflowOptions provides configuration for a PlaceholderWorkflow workflow operation
type PlaceholderWorkflowOptions struct {
	options                  client.StartWorkflowOptions
	executionTimeout         *time.Duration
	id                       *string
	idReusePolicy            enumsv1.WorkflowIdReusePolicy
	retryPolicy              *temporal.RetryPolicy
	runTimeout               *time.Duration
	searchAttributes         map[string]any
	taskQueue                *string
	taskTimeout              *time.Duration
	typedSearchAttributes    *temporal.SearchAttributes
	enableEagerStart         *bool
	workflowIdConflictPolicy enumsv1.WorkflowIdConflictPolicy
}

// NewPlaceholderWorkflowOptions initializes a new PlaceholderWorkflowOptions value
func NewPlaceholderWorkflowOptions() *PlaceholderWorkflowOptions {
	return &PlaceholderWorkflowOptions{}
}

// Build initializes a new go.temporal.io/sdk/client.StartWorkflowOptions value with defaults and overrides applied
func (o *PlaceholderWorkflowOptions) Build(req protoreflect.Message) (client.StartWorkflowOptions, error) {
	opts := o.options
	if v := o.id; v != nil {
		opts.ID = *v
	}
	if v := o.idReusePolicy; v != enumsv1.WORKFLOW_ID_REUSE_POLICY_UNSPECIFIED {
		opts.WorkflowIDReusePolicy = v
	}
	if v := o.workflowIdConflictPolicy; v != enumsv1.WORKFLOW_ID_CONFLICT_POLICY_UNSPECIFIED {
		opts.WorkflowIDConflictPolicy = v
	}
	if v := o.taskQueue; v != nil {
		opts.TaskQueue = *v
	} else if opts.TaskQueue == "" {
		opts.TaskQueue = TestServiceTaskQueue
	}
	if v := o.retryPolicy; v != nil {
		opts.RetryPolicy = v
	} else if opts.RetryPolicy == nil {
		opts.RetryPolicy = &temporal.RetryPolicy{
			MaximumAttempts: int32(1),
		}
	}
	if v := o.searchAttributes; v != nil {
		opts.SearchAttributes = o.searchAttributes
	}
	if v := o.typedSearchAttributes; v != nil {
		opts.TypedSearchAttributes = *v
	}
	if v := o.enableEagerStart; v != nil {
		opts.EnableEagerStart = *v
	}
	if v := o.executionTimeout; v != nil {
		opts.WorkflowExecutionTimeout = *v
	}
	if v := o.runTimeout; v != nil {
		opts.WorkflowRunTimeout = *v
	}
	if v := o.taskTimeout; v != nil {
		opts.WorkflowTaskTimeout = *v
	}
	return opts, nil
}

// WithStartWorkflowOptions sets the initial go.temporal.io/sdk/client.StartWorkflowOptions
func (o *PlaceholderWorkflowOptions) WithStartWorkflowOptions(options client.StartWorkflowOptions) *PlaceholderWorkflowOptions {
	o.options = options
	return o
}

// WithEnableEagerStart sets the EnableEagerStart value
func (o *PlaceholderWorkflowOptions) WithEnableEagerStart(enable bool) *PlaceholderWorkflowOptions {
	o.enableEagerStart = &enable
	return o
}

// WithExecutionTimeout sets the WorkflowExecutionTimeout value
func (o *PlaceholderWorkflowOptions) WithExecutionTimeout(d time.Duration) *PlaceholderWorkflowOptions {
	o.executionTimeout = &d
	return o
}

// WithID sets the ID value
func (o *PlaceholderWorkflowOptions) WithID(id string) *PlaceholderWorkflowOptions {
	o.id = &id
	return o
}

// WithIDReusePolicy sets the WorkflowIDReusePolicy value
func (o *PlaceholderWorkflowOptions) WithIDReusePolicy(policy enumsv1.WorkflowIdReusePolicy) *PlaceholderWorkflowOptions {
	o.idReusePolicy = policy
	return o
}

// WithRetryPolicy sets the RetryPolicy value
func (o *PlaceholderWorkflowOptions) WithRetryPolicy(policy *temporal.RetryPolicy) *PlaceholderWorkflowOptions {
	o.retryPolicy = policy
	return o
}

// WithRunTimeout sets the WorkflowRunTimeout value
func (o *PlaceholderWorkflowOptions) WithRunTimeout(d time.Duration) *PlaceholderWorkflowOptions {
	o.runTimeout = &d
	return o
}

// WithSearchAttributes sets the SearchAttributes value
func (o *PlaceholderWorkflowOptions) WithSearchAttributes(sa map[string]any) *PlaceholderWorkflowOptions {
	o.searchAttributes = sa
	return o
}

// WithTaskTimeout sets the WorkflowTaskTimeout value
func (o *PlaceholderWorkflowOptions) WithTaskTimeout(d time.Duration) *PlaceholderWorkflowOptions {
	o.taskTimeout = &d
	return o
}

// WithTaskQueue sets the TaskQueue value
func (o *PlaceholderWorkflowOptions) WithTaskQueue(tq string) *PlaceholderWorkflowOptions {
	o.taskQueue = &tq
	return o
}

// WithTypedSearchAttributes sets the TypedSearchAttributes value
func (o *PlaceholderWorkflowOptions) WithTypedSearchAttributes(tsa temporal.SearchAttributes) *PlaceholderWorkflowOptions {
	o.typedSearchAttributes = &tsa
	return o
}

// WithWorkflowIdConflictPolicy sets the WorkflowIdConflictPolicy value
func (o *PlaceholderWorkflowOptions) WithWorkflowIdConflictPolicy(policy enumsv1.WorkflowIdConflictPolicy) *PlaceholderWorkflowOptions {
	o.workflowIdConflictPolicy = policy
	return o
}

// PlaceholderWorkflowRun describes a(n) PlaceholderWorkflow workflow run
type PlaceholderWorkflowRun interface {
	// ID returns the workflow ID
	ID() string

	// RunID returns the workflow instance ID
	RunID() string

	// Run returns the inner client.WorkflowRun
	Run() client.WorkflowRun

	// Get blocks until the workflow is complete and returns the result
	Get(ctx context.Context) (*PlaceholderWorkflowResponse, error)

	// Cancel requests cancellation of a workflow in execution, returning an error if applicable
	Cancel(ctx context.Context) error

	// Terminate terminates a workflow in execution, returning an error if applicable
	Terminate(ctx context.Context, reason string, details ...interface{}) error
}

// placeholderWorkflowRun provides an internal implementation of a(n) PlaceholderWorkflowRunRun
type placeholderWorkflowRun struct {
	client *testServiceClient
	run    client.WorkflowRun
}

// ID returns the workflow ID
func (r *placeholderWorkflowRun) ID() string {
	return r.run.GetID()
}

// Run returns the inner client.WorkflowRun
func (r *placeholderWorkflowRun) Run() client.WorkflowRun {
	return r.run
}

// RunID returns the execution ID
func (r *placeholderWorkflowRun) RunID() string {
	return r.run.GetRunID()
}

// Cancel requests cancellation of a workflow in execution, returning an error if applicable
func (r *placeholderWorkflowRun) Cancel(ctx context.Context) error {
	return r.client.CancelWorkflow(ctx, r.ID(), r.RunID())
}

// Get blocks until the workflow is complete, returning the result if applicable
func (r *placeholderWorkflowRun) Get(ctx context.Context) (*PlaceholderWorkflowResponse, error) {
	var resp PlaceholderWorkflowResponse
	if err := r.run.Get(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Terminate terminates a workflow in execution, returning an error if applicable
func (r *placeholderWorkflowRun) Terminate(ctx context.Context, reason string, details ...interface{}) error {
	return r.client.TerminateWorkflow(ctx, r.ID(), r.RunID(), reason, details...)
}

// Reference to generated workflow functions
var (
	// testServiceRegistrationMutex is a mutex for registering cloud.v1.workflow.TestService workflows
	testServiceRegistrationMutex sync.Mutex
	// PlaceholderWorkflow: see the message doc above — required by the
	// code generator, never started.
	PlaceholderWorkflowFunction func(workflow.Context, *PlaceholderWorkflowRequest) (*PlaceholderWorkflowResponse, error)
)

// TestServiceWorkflowFunctions describes a mockable dependency for inlining workflows within other workflows
type (
	// TestServiceWorkflowFunctions describes a mockable dependency for inlining workflows within other workflows
	TestServiceWorkflowFunctions interface {
		// PlaceholderWorkflow: see the message doc above — required by the
		// code generator, never started.
		PlaceholderWorkflow(workflow.Context, *PlaceholderWorkflowRequest) (*PlaceholderWorkflowResponse, error)
	}
	// testServiceWorkflowFunctions provides an internal TestServiceWorkflowFunctions implementation
	testServiceWorkflowFunctions struct{}
)

func NewTestServiceWorkflowFunctions() TestServiceWorkflowFunctions {
	return &testServiceWorkflowFunctions{}
}

// PlaceholderWorkflow: see the message doc above — required by the
// code generator, never started.
func (f *testServiceWorkflowFunctions) PlaceholderWorkflow(ctx workflow.Context, req *PlaceholderWorkflowRequest) (*PlaceholderWorkflowResponse, error) {
	if PlaceholderWorkflowFunction == nil {
		return nil, errors.New("PlaceholderWorkflow requires workflow registration via RegisterTestServiceWorkflows or RegisterPlaceholderWorkflowWorkflow")
	}
	return PlaceholderWorkflowFunction(ctx, req)
}

// TestServiceWorkflows provides methods for initializing new cloud.v1.workflow.TestService workflow values
type TestServiceWorkflows interface {
	// PlaceholderWorkflow: see the message doc above — required by the
	// code generator, never started.
	PlaceholderWorkflow(ctx workflow.Context, input *PlaceholderWorkflowWorkflowInput) (PlaceholderWorkflowWorkflow, error)
}

// RegisterTestServiceWorkflows registers cloud.v1.workflow.TestService workflows with the given worker
func RegisterTestServiceWorkflows(r worker.WorkflowRegistry, workflows TestServiceWorkflows) {
	RegisterPlaceholderWorkflowWorkflow(r, workflows.PlaceholderWorkflow)
}

// RegisterPlaceholderWorkflowWorkflow registers a cloud.v1.workflow.TestService.PlaceholderWorkflow workflow with the given worker
func RegisterPlaceholderWorkflowWorkflow(r worker.WorkflowRegistry, wf func(workflow.Context, *PlaceholderWorkflowWorkflowInput) (PlaceholderWorkflowWorkflow, error)) {
	testServiceRegistrationMutex.Lock()
	defer testServiceRegistrationMutex.Unlock()
	PlaceholderWorkflowFunction = buildPlaceholderWorkflow(wf)
	r.RegisterWorkflowWithOptions(PlaceholderWorkflowFunction, workflow.RegisterOptions{Name: PlaceholderWorkflowWorkflowName})
}

// buildPlaceholderWorkflow converts a PlaceholderWorkflow workflow struct into a valid workflow function
func buildPlaceholderWorkflow(ctor func(workflow.Context, *PlaceholderWorkflowWorkflowInput) (PlaceholderWorkflowWorkflow, error)) func(workflow.Context, *PlaceholderWorkflowRequest) (*PlaceholderWorkflowResponse, error) {
	return func(ctx workflow.Context, req *PlaceholderWorkflowRequest) (*PlaceholderWorkflowResponse, error) {
		input := &PlaceholderWorkflowWorkflowInput{
			Req: req,
		}
		wf, err := ctor(ctx, input)
		if err != nil {
			return nil, err
		}
		if initializable, ok := wf.(helpers.Initializable); ok {
			if err := initializable.Initialize(ctx); err != nil {
				return nil, err
			}
		}
		return wf.Execute(ctx)
	}
}

// PlaceholderWorkflowWorkflowInput describes the input to a(n) PlaceholderWorkflow workflow constructor
type PlaceholderWorkflowWorkflowInput struct {
	Req *PlaceholderWorkflowRequest
}

// ContinueAsNew returns an appropriately configured ContinueAsNewError
func (i *PlaceholderWorkflowWorkflowInput) ContinueAsNew(ctx workflow.Context, input *PlaceholderWorkflowRequest, options ...workflow.ContinueAsNewErrorOptions) (*PlaceholderWorkflowResponse, error) {
	next := i.Req
	if input != nil {
		next = input
	}
	if len(options) > 0 {
		return nil, workflow.NewContinueAsNewErrorWithOptions(ctx, options[0], PlaceholderWorkflowWorkflowName, next)
	}
	return nil, workflow.NewContinueAsNewError(ctx, PlaceholderWorkflowWorkflowName, next)
}

// PlaceholderWorkflow: see the message doc above — required by the
// code generator, never started.
type PlaceholderWorkflowWorkflow interface {
	// Execute defines the entrypoint to a(n) PlaceholderWorkflow workflow
	Execute(ctx workflow.Context) (*PlaceholderWorkflowResponse, error)
}

// PlaceholderWorkflow: see the message doc above — required by the
// code generator, never started.
func PlaceholderWorkflowChild(ctx workflow.Context, req *PlaceholderWorkflowRequest, options ...*PlaceholderWorkflowChildOptions) (*PlaceholderWorkflowResponse, error) {
	childRun, err := PlaceholderWorkflowChildAsync(ctx, req, options...)
	if err != nil {
		return nil, err
	}
	return childRun.Get(ctx)
}

// PlaceholderWorkflow: see the message doc above — required by the
// code generator, never started.
func PlaceholderWorkflowChildAsync(ctx workflow.Context, req *PlaceholderWorkflowRequest, options ...*PlaceholderWorkflowChildOptions) (*PlaceholderWorkflowChildRun, error) {
	var o *PlaceholderWorkflowChildOptions
	if len(options) > 0 && options[0] != nil {
		o = options[0]
	} else {
		o = NewPlaceholderWorkflowChildOptions()
	}
	opts, err := o.Build(ctx, req.ProtoReflect())
	if err != nil {
		return nil, fmt.Errorf("error initializing workflow.ChildWorkflowOptions: %w", err)
	}
	ctx = workflow.WithChildOptions(ctx, opts)
	if o.dc != nil {
		ctx = workflow.WithDataConverter(ctx, o.dc)
	}
	return &PlaceholderWorkflowChildRun{Future: workflow.ExecuteChildWorkflow(ctx, PlaceholderWorkflowWorkflowName, req)}, nil
}

// PlaceholderWorkflowChildOptions provides configuration for a child PlaceholderWorkflow workflow operation
type PlaceholderWorkflowChildOptions struct {
	options               workflow.ChildWorkflowOptions
	executionTimeout      *time.Duration
	id                    *string
	idReusePolicy         enumsv1.WorkflowIdReusePolicy
	retryPolicy           *temporal.RetryPolicy
	runTimeout            *time.Duration
	searchAttributes      map[string]any
	taskQueue             *string
	taskTimeout           *time.Duration
	typedSearchAttributes *temporal.SearchAttributes
	dc                    converter.DataConverter
	parentClosePolicy     enumsv1.ParentClosePolicy
	waitForCancellation   *bool
}

// NewPlaceholderWorkflowChildOptions initializes a new PlaceholderWorkflowChildOptions value
func NewPlaceholderWorkflowChildOptions() *PlaceholderWorkflowChildOptions {
	return &PlaceholderWorkflowChildOptions{}
}

// Build initializes a new go.temporal.io/sdk/workflow.ChildWorkflowOptions value with defaults and overrides applied
func (o *PlaceholderWorkflowChildOptions) Build(ctx workflow.Context, req protoreflect.Message) (workflow.ChildWorkflowOptions, error) {
	opts := o.options
	if v := o.id; v != nil {
		opts.WorkflowID = *v
	}
	if v := o.idReusePolicy; v != enumsv1.WORKFLOW_ID_REUSE_POLICY_UNSPECIFIED {
		opts.WorkflowIDReusePolicy = v
	}
	if v := o.taskQueue; v != nil {
		opts.TaskQueue = *v
	} else if opts.TaskQueue == "" {
		opts.TaskQueue = TestServiceTaskQueue
	}
	if v := o.retryPolicy; v != nil {
		opts.RetryPolicy = v
	} else if opts.RetryPolicy == nil {
		opts.RetryPolicy = &temporal.RetryPolicy{
			MaximumAttempts: int32(1),
		}
	}
	if v := o.searchAttributes; v != nil {
		opts.SearchAttributes = o.searchAttributes
	}
	if v := o.typedSearchAttributes; v != nil {
		opts.TypedSearchAttributes = *v
	}
	if v := o.executionTimeout; v != nil {
		opts.WorkflowExecutionTimeout = *v
	}
	if v := o.runTimeout; v != nil {
		opts.WorkflowRunTimeout = *v
	}
	if v := o.taskTimeout; v != nil {
		opts.WorkflowTaskTimeout = *v
	}
	if v := o.parentClosePolicy; v != enumsv1.PARENT_CLOSE_POLICY_UNSPECIFIED {
		opts.ParentClosePolicy = v
	}
	if v := o.waitForCancellation; v != nil {
		opts.WaitForCancellation = *v
	}
	return opts, nil
}

// WithChildWorkflowOptions sets the initial go.temporal.io/sdk/workflow.ChildWorkflowOptions
func (o *PlaceholderWorkflowChildOptions) WithChildWorkflowOptions(options workflow.ChildWorkflowOptions) *PlaceholderWorkflowChildOptions {
	o.options = options
	return o
}

// WithDataConverter registers a DataConverter for the child workflow
func (o *PlaceholderWorkflowChildOptions) WithDataConverter(dc converter.DataConverter) *PlaceholderWorkflowChildOptions {
	o.dc = dc
	return o
}

// WithExecutionTimeout sets the WorkflowExecutionTimeout value
func (o *PlaceholderWorkflowChildOptions) WithExecutionTimeout(d time.Duration) *PlaceholderWorkflowChildOptions {
	o.executionTimeout = &d
	return o
}

// WithID sets the WorkflowID value
func (o *PlaceholderWorkflowChildOptions) WithID(id string) *PlaceholderWorkflowChildOptions {
	o.id = &id
	return o
}

// WithIDReusePolicy sets the WorkflowIDReusePolicy value
func (o *PlaceholderWorkflowChildOptions) WithIDReusePolicy(policy enumsv1.WorkflowIdReusePolicy) *PlaceholderWorkflowChildOptions {
	o.idReusePolicy = policy
	return o
}

// WithParentClosePolicy sets the WorkflowIDReusePolicy value
func (o *PlaceholderWorkflowChildOptions) WithParentClosePolicy(policy enumsv1.ParentClosePolicy) *PlaceholderWorkflowChildOptions {
	o.parentClosePolicy = policy
	return o
}

// WithRetryPolicy sets the RetryPolicy value
func (o *PlaceholderWorkflowChildOptions) WithRetryPolicy(policy *temporal.RetryPolicy) *PlaceholderWorkflowChildOptions {
	o.retryPolicy = policy
	return o
}

// WithRunTimeout sets the WorkflowRunTimeout value
func (o *PlaceholderWorkflowChildOptions) WithRunTimeout(d time.Duration) *PlaceholderWorkflowChildOptions {
	o.runTimeout = &d
	return o
}

// WithSearchAttributes sets the SearchAttributes value
func (o *PlaceholderWorkflowChildOptions) WithSearchAttributes(sa map[string]any) *PlaceholderWorkflowChildOptions {
	o.searchAttributes = sa
	return o
}

// WithTaskTimeout sets the WorkflowTaskTimeout value
func (o *PlaceholderWorkflowChildOptions) WithTaskTimeout(d time.Duration) *PlaceholderWorkflowChildOptions {
	o.taskTimeout = &d
	return o
}

// WithTaskQueue sets the TaskQueue value
func (o *PlaceholderWorkflowChildOptions) WithTaskQueue(tq string) *PlaceholderWorkflowChildOptions {
	o.taskQueue = &tq
	return o
}

// WithTypedSearchAttributes sets the TypedSearchAttributes value
func (o *PlaceholderWorkflowChildOptions) WithTypedSearchAttributes(tsa temporal.SearchAttributes) *PlaceholderWorkflowChildOptions {
	o.typedSearchAttributes = &tsa
	return o
}

// WithWaitForCancellation sets the WaitForCancellation value
func (o *PlaceholderWorkflowChildOptions) WithWaitForCancellation(wait bool) *PlaceholderWorkflowChildOptions {
	o.waitForCancellation = &wait
	return o
}

// PlaceholderWorkflowChildRun describes a child PlaceholderWorkflow workflow run
type PlaceholderWorkflowChildRun struct {
	Future workflow.ChildWorkflowFuture
}

// Get blocks until the workflow is completed, returning the response value
func (r *PlaceholderWorkflowChildRun) Get(ctx workflow.Context) (*PlaceholderWorkflowResponse, error) {
	var resp PlaceholderWorkflowResponse
	if err := r.Future.Get(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Select adds this completion to the selector. Callback can be nil.
func (r *PlaceholderWorkflowChildRun) Select(sel workflow.Selector, fn func(*PlaceholderWorkflowChildRun)) workflow.Selector {
	return sel.AddFuture(r.Future, func(workflow.Future) {
		if fn != nil {
			fn(r)
		}
	})
}

// SelectStart adds waiting for start to the selector. Callback can be nil.
func (r *PlaceholderWorkflowChildRun) SelectStart(sel workflow.Selector, fn func(*PlaceholderWorkflowChildRun)) workflow.Selector {
	return sel.AddFuture(r.Future.GetChildWorkflowExecution(), func(workflow.Future) {
		if fn != nil {
			fn(r)
		}
	})
}

// WaitStart waits for the child workflow to start
func (r *PlaceholderWorkflowChildRun) WaitStart(ctx workflow.Context) (*workflow.Execution, error) {
	var exec workflow.Execution
	if err := r.Future.GetChildWorkflowExecution().Get(ctx, &exec); err != nil {
		return nil, err
	}
	return &exec, nil
}

// UpdateStageSignal describes a(n) cloud.v1.workflow.TestService.UpdateStage signal
type UpdateStageSignal struct {
	Channel workflow.ReceiveChannel
}

// NewUpdateStageSignal initializes a new UpdateStage signal wrapper
func NewUpdateStageSignal(ctx workflow.Context) *UpdateStageSignal {
	return &UpdateStageSignal{Channel: workflow.GetSignalChannel(ctx, UpdateStageSignalName)}
}

// Receive blocks until a(n) cloud.v1.workflow.TestService.UpdateStage signal is received
func (s *UpdateStageSignal) Receive(ctx workflow.Context) (*StageUpdate, bool) {
	var resp StageUpdate
	more := s.Channel.Receive(ctx, &resp)
	return &resp, more
}

// ReceiveAsync checks for a cloud.v1.workflow.TestService.UpdateStage signal without blocking
func (s *UpdateStageSignal) ReceiveAsync() *StageUpdate {
	var resp StageUpdate
	if ok := s.Channel.ReceiveAsync(&resp); !ok {
		return nil
	}
	return &resp
}

// ReceiveWithTimeout blocks until a(n) cloud.v1.workflow.TestService.UpdateStage signal is received or timeout expires.
// Returns more value of false when Channel is closed.
// Returns ok value of false when no value was found in the channel for the duration of timeout or the ctx was canceled.
// resp will be nil if ok is false.
func (s *UpdateStageSignal) ReceiveWithTimeout(ctx workflow.Context, timeout time.Duration) (resp *StageUpdate, ok bool, more bool) {
	resp = &StageUpdate{}
	if ok, more = s.Channel.ReceiveWithTimeout(ctx, timeout, &resp); !ok {
		return nil, false, more
	}
	return
}

// Select checks for a(n) cloud.v1.workflow.TestService.UpdateStage signal without blocking
func (s *UpdateStageSignal) Select(sel workflow.Selector, fn func(*StageUpdate)) workflow.Selector {
	return sel.AddReceive(s.Channel, func(workflow.ReceiveChannel, bool) {
		req := s.ReceiveAsync()
		if fn != nil {
			fn(req)
		}
	})
}

// UpdateStage is a Temporal signal used by child workflows to update one
// concrete runtime stage inside the parent TestWorkflow RunState.
func UpdateStageExternal(ctx workflow.Context, workflowID string, runID string, req *StageUpdate) error {
	return UpdateStageExternalAsync(ctx, workflowID, runID, req).Get(ctx, nil)
}

// UpdateStage is a Temporal signal used by child workflows to update one
// concrete runtime stage inside the parent TestWorkflow RunState.
func UpdateStageExternalAsync(ctx workflow.Context, workflowID string, runID string, req *StageUpdate) workflow.Future {
	return workflow.SignalExternalWorkflow(ctx, workflowID, runID, UpdateStageSignalName, req)
}

// TestServiceActivities describes available worker activities
type TestServiceActivities interface{}

// RegisterTestServiceActivities registers activities with a worker
func RegisterTestServiceActivities(r worker.ActivityRegistry, activities TestServiceActivities) {}

// TestClient provides a testsuite-compatible Client
type TestTestServiceClient struct {
	env       *testsuite.TestWorkflowEnvironment
	workflows TestServiceWorkflows
}

var _ TestServiceClient = &TestTestServiceClient{}

// NewTestTestServiceClient initializes a new TestTestServiceClient value
func NewTestTestServiceClient(env *testsuite.TestWorkflowEnvironment, workflows TestServiceWorkflows, activities TestServiceActivities) *TestTestServiceClient {
	if workflows != nil {
		RegisterTestServiceWorkflows(env, workflows)
	}
	if activities != nil {
		RegisterTestServiceActivities(env, activities)
	}
	return &TestTestServiceClient{env, workflows}
}

// PlaceholderWorkflow executes a(n) PlaceholderWorkflow workflow in the test environment
func (c *TestTestServiceClient) PlaceholderWorkflow(ctx context.Context, req *PlaceholderWorkflowRequest, opts ...*PlaceholderWorkflowOptions) (*PlaceholderWorkflowResponse, error) {
	run, err := c.PlaceholderWorkflowAsync(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return run.Get(ctx)
}

// PlaceholderWorkflowAsync executes a(n) PlaceholderWorkflow workflow in the test environment
func (c *TestTestServiceClient) PlaceholderWorkflowAsync(ctx context.Context, req *PlaceholderWorkflowRequest, options ...*PlaceholderWorkflowOptions) (PlaceholderWorkflowRun, error) {
	var o *PlaceholderWorkflowOptions
	if len(options) > 0 && options[0] != nil {
		o = options[0]
	} else {
		o = NewPlaceholderWorkflowOptions()
	}
	opts, err := o.Build(req.ProtoReflect())
	if err != nil {
		return nil, fmt.Errorf("error initializing client.StartWorkflowOptions: %w", err)
	}
	return &testPlaceholderWorkflowRun{client: c, env: c.env, opts: &opts, req: req, workflows: c.workflows}, nil
}

// GetPlaceholderWorkflow is a noop
func (c *TestTestServiceClient) GetPlaceholderWorkflow(ctx context.Context, workflowID string, runID string) PlaceholderWorkflowRun {
	return &testPlaceholderWorkflowRun{env: c.env, workflows: c.workflows}
}

// CancelWorkflow requests cancellation of an existing workflow execution
func (c *TestTestServiceClient) CancelWorkflow(ctx context.Context, workflowID string, runID string) error {
	c.env.CancelWorkflow()
	return nil
}

// TerminateWorkflow terminates an existing workflow execution
func (c *TestTestServiceClient) TerminateWorkflow(ctx context.Context, workflowID string, runID string, reason string, details ...interface{}) error {
	return c.CancelWorkflow(ctx, workflowID, runID)
}

// GetRunState executes a GetRunState query
func (c *TestTestServiceClient) GetRunState(ctx context.Context, workflowID string, runID string) (*RunState, error) {
	val, err := c.env.QueryWorkflow(GetRunStateQueryName)
	if err != nil {
		return nil, err
	} else if !val.HasValue() {
		return nil, nil
	} else {
		var result RunState
		if err := val.Get(&result); err != nil {
			return nil, err
		}
		return &result, nil
	}
}

// UpdateStage executes a UpdateStage signal
func (c *TestTestServiceClient) UpdateStage(ctx context.Context, workflowID string, runID string, req *StageUpdate) error {
	c.env.SignalWorkflow(UpdateStageSignalName, req)
	return nil
}

var _ PlaceholderWorkflowRun = &testPlaceholderWorkflowRun{}

// testPlaceholderWorkflowRun provides convenience methods for interacting with a(n) PlaceholderWorkflow workflow in the test environment
type testPlaceholderWorkflowRun struct {
	client    *TestTestServiceClient
	env       *testsuite.TestWorkflowEnvironment
	isStarted atomic.Bool
	opts      *client.StartWorkflowOptions
	req       *PlaceholderWorkflowRequest
	workflows TestServiceWorkflows
}

// Cancel requests cancellation of a workflow in execution, returning an error if applicable
func (r *testPlaceholderWorkflowRun) Cancel(ctx context.Context) error {
	return r.client.CancelWorkflow(ctx, r.ID(), r.RunID())
}

// Get retrieves a test PlaceholderWorkflow workflow result
func (r *testPlaceholderWorkflowRun) Get(context.Context) (*PlaceholderWorkflowResponse, error) {
	if r.isStarted.CompareAndSwap(false, true) {
		r.env.ExecuteWorkflow(PlaceholderWorkflowWorkflowName, r.req)
	}
	if !r.env.IsWorkflowCompleted() {
		return nil, errors.New("workflow in progress")
	}
	if err := r.env.GetWorkflowError(); err != nil {
		return nil, err
	}
	var result PlaceholderWorkflowResponse
	if err := r.env.GetWorkflowResult(&result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ID returns a test PlaceholderWorkflow workflow run's workflow ID
func (r *testPlaceholderWorkflowRun) ID() string {
	if r.opts != nil {
		return r.opts.ID
	}
	return ""
}

// Run noop implementation
func (r *testPlaceholderWorkflowRun) Run() client.WorkflowRun {
	return nil
}

// RunID noop implementation
func (r *testPlaceholderWorkflowRun) RunID() string {
	return ""
}

// Terminate terminates a workflow in execution, returning an error if applicable
func (r *testPlaceholderWorkflowRun) Terminate(ctx context.Context, reason string, details ...interface{}) error {
	return r.client.TerminateWorkflow(ctx, r.ID(), r.RunID(), reason, details...)
}

// WithTestServiceSchemeTypes registers all TestService protobuf types with the given scheme
func WithTestServiceSchemeTypes() scheme.Option {
	return func(s *scheme.Scheme) {
		s.RegisterType(File_cloud_v1_workflow_test_proto.Messages().ByName("RunState"))
		s.RegisterType(File_cloud_v1_workflow_test_proto.Messages().ByName("StageUpdate"))
		s.RegisterType(File_cloud_v1_workflow_test_proto.Messages().ByName("PlaceholderWorkflowRequest"))
		s.RegisterType(File_cloud_v1_workflow_test_proto.Messages().ByName("PlaceholderWorkflowResponse"))
	}
}
