// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: cloud/v1/workflow/test.proto

package workflow

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TestApi_TestWorkflow_FullMethodName            = "/cloud.v1.workflow.TestApi/TestWorkflow"
	TestApi_InstallStroppyWorkflow_FullMethodName  = "/cloud.v1.workflow.TestApi/InstallStroppyWorkflow"
	TestApi_InstallDatabaseWorkflow_FullMethodName = "/cloud.v1.workflow.TestApi/InstallDatabaseWorkflow"
	TestApi_RunWorkloadWorkflow_FullMethodName     = "/cloud.v1.workflow.TestApi/RunWorkloadWorkflow"
)

// TestApiClient is the client API for TestApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TestWorkflow orchestrates one full test cycle:
//
//	deploy -> install stroppy -> [install database unless external] -> run workload -> teardown.
//
// It composes child workflows; topology stays baked, only runtime info from the
// deployment is carried forward.
type TestApiClient interface {
	TestWorkflow(ctx context.Context, in *TestWorkflowRequest, opts ...grpc.CallOption) (*TestWorkflowResponse, error)
	InstallStroppyWorkflow(ctx context.Context, in *InstallStroppyWorkflowRequest, opts ...grpc.CallOption) (*InstallStroppyWorkflowResponse, error)
	InstallDatabaseWorkflow(ctx context.Context, in *InstallDatabaseWorkflowRequest, opts ...grpc.CallOption) (*InstallDatabaseWorkflowResponse, error)
	RunWorkloadWorkflow(ctx context.Context, in *RunWorkloadWorkflowRequest, opts ...grpc.CallOption) (*RunWorkloadWorkflowResponse, error)
}

type testApiClient struct {
	cc grpc.ClientConnInterface
}

func NewTestApiClient(cc grpc.ClientConnInterface) TestApiClient {
	return &testApiClient{cc}
}

func (c *testApiClient) TestWorkflow(ctx context.Context, in *TestWorkflowRequest, opts ...grpc.CallOption) (*TestWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestWorkflowResponse)
	err := c.cc.Invoke(ctx, TestApi_TestWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testApiClient) InstallStroppyWorkflow(ctx context.Context, in *InstallStroppyWorkflowRequest, opts ...grpc.CallOption) (*InstallStroppyWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallStroppyWorkflowResponse)
	err := c.cc.Invoke(ctx, TestApi_InstallStroppyWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testApiClient) InstallDatabaseWorkflow(ctx context.Context, in *InstallDatabaseWorkflowRequest, opts ...grpc.CallOption) (*InstallDatabaseWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallDatabaseWorkflowResponse)
	err := c.cc.Invoke(ctx, TestApi_InstallDatabaseWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testApiClient) RunWorkloadWorkflow(ctx context.Context, in *RunWorkloadWorkflowRequest, opts ...grpc.CallOption) (*RunWorkloadWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunWorkloadWorkflowResponse)
	err := c.cc.Invoke(ctx, TestApi_RunWorkloadWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestApiServer is the server API for TestApi service.
// All implementations must embed UnimplementedTestApiServer
// for forward compatibility.
//
// TestWorkflow orchestrates one full test cycle:
//
//	deploy -> install stroppy -> [install database unless external] -> run workload -> teardown.
//
// It composes child workflows; topology stays baked, only runtime info from the
// deployment is carried forward.
type TestApiServer interface {
	TestWorkflow(context.Context, *TestWorkflowRequest) (*TestWorkflowResponse, error)
	InstallStroppyWorkflow(context.Context, *InstallStroppyWorkflowRequest) (*InstallStroppyWorkflowResponse, error)
	InstallDatabaseWorkflow(context.Context, *InstallDatabaseWorkflowRequest) (*InstallDatabaseWorkflowResponse, error)
	RunWorkloadWorkflow(context.Context, *RunWorkloadWorkflowRequest) (*RunWorkloadWorkflowResponse, error)
	mustEmbedUnimplementedTestApiServer()
}

// UnimplementedTestApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTestApiServer struct{}

func (UnimplementedTestApiServer) TestWorkflow(context.Context, *TestWorkflowRequest) (*TestWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestWorkflow not implemented")
}
func (UnimplementedTestApiServer) InstallStroppyWorkflow(context.Context, *InstallStroppyWorkflowRequest) (*InstallStroppyWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallStroppyWorkflow not implemented")
}
func (UnimplementedTestApiServer) InstallDatabaseWorkflow(context.Context, *InstallDatabaseWorkflowRequest) (*InstallDatabaseWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallDatabaseWorkflow not implemented")
}
func (UnimplementedTestApiServer) RunWorkloadWorkflow(context.Context, *RunWorkloadWorkflowRequest) (*RunWorkloadWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunWorkloadWorkflow not implemented")
}
func (UnimplementedTestApiServer) mustEmbedUnimplementedTestApiServer() {}
func (UnimplementedTestApiServer) testEmbeddedByValue()                 {}

// UnsafeTestApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestApiServer will
// result in compilation errors.
type UnsafeTestApiServer interface {
	mustEmbedUnimplementedTestApiServer()
}

func RegisterTestApiServer(s grpc.ServiceRegistrar, srv TestApiServer) {
	// If the following call panics, it indicates UnimplementedTestApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TestApi_ServiceDesc, srv)
}

func _TestApi_TestWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestApiServer).TestWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestApi_TestWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestApiServer).TestWorkflow(ctx, req.(*TestWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestApi_InstallStroppyWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallStroppyWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestApiServer).InstallStroppyWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestApi_InstallStroppyWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestApiServer).InstallStroppyWorkflow(ctx, req.(*InstallStroppyWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestApi_InstallDatabaseWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallDatabaseWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestApiServer).InstallDatabaseWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestApi_InstallDatabaseWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestApiServer).InstallDatabaseWorkflow(ctx, req.(*InstallDatabaseWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestApi_RunWorkloadWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunWorkloadWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestApiServer).RunWorkloadWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestApi_RunWorkloadWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestApiServer).RunWorkloadWorkflow(ctx, req.(*RunWorkloadWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TestApi_ServiceDesc is the grpc.ServiceDesc for TestApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.v1.workflow.TestApi",
	HandlerType: (*TestApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestWorkflow",
			Handler:    _TestApi_TestWorkflow_Handler,
		},
		{
			MethodName: "InstallStroppyWorkflow",
			Handler:    _TestApi_InstallStroppyWorkflow_Handler,
		},
		{
			MethodName: "InstallDatabaseWorkflow",
			Handler:    _TestApi_InstallDatabaseWorkflow_Handler,
		},
		{
			MethodName: "RunWorkloadWorkflow",
			Handler:    _TestApi_RunWorkloadWorkflow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cloud/v1/workflow/test.proto",
}

const (
	SuiteWorkflowApi_SuiteWorkflow_FullMethodName = "/cloud.v1.workflow.SuiteWorkflowApi/SuiteWorkflow"
)

// SuiteWorkflowApiClient is the client API for SuiteWorkflowApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SuiteWorkflow runs a child TestWorkflow per test_run, honoring max_parallel.
type SuiteWorkflowApiClient interface {
	SuiteWorkflow(ctx context.Context, in *SuiteWorkflowRequest, opts ...grpc.CallOption) (*SuiteWorkflowResponse, error)
}

type suiteWorkflowApiClient struct {
	cc grpc.ClientConnInterface
}

func NewSuiteWorkflowApiClient(cc grpc.ClientConnInterface) SuiteWorkflowApiClient {
	return &suiteWorkflowApiClient{cc}
}

func (c *suiteWorkflowApiClient) SuiteWorkflow(ctx context.Context, in *SuiteWorkflowRequest, opts ...grpc.CallOption) (*SuiteWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuiteWorkflowResponse)
	err := c.cc.Invoke(ctx, SuiteWorkflowApi_SuiteWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SuiteWorkflowApiServer is the server API for SuiteWorkflowApi service.
// All implementations must embed UnimplementedSuiteWorkflowApiServer
// for forward compatibility.
//
// SuiteWorkflow runs a child TestWorkflow per test_run, honoring max_parallel.
type SuiteWorkflowApiServer interface {
	SuiteWorkflow(context.Context, *SuiteWorkflowRequest) (*SuiteWorkflowResponse, error)
	mustEmbedUnimplementedSuiteWorkflowApiServer()
}

// UnimplementedSuiteWorkflowApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSuiteWorkflowApiServer struct{}

func (UnimplementedSuiteWorkflowApiServer) SuiteWorkflow(context.Context, *SuiteWorkflowRequest) (*SuiteWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuiteWorkflow not implemented")
}
func (UnimplementedSuiteWorkflowApiServer) mustEmbedUnimplementedSuiteWorkflowApiServer() {}
func (UnimplementedSuiteWorkflowApiServer) testEmbeddedByValue()                          {}

// UnsafeSuiteWorkflowApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SuiteWorkflowApiServer will
// result in compilation errors.
type UnsafeSuiteWorkflowApiServer interface {
	mustEmbedUnimplementedSuiteWorkflowApiServer()
}

func RegisterSuiteWorkflowApiServer(s grpc.ServiceRegistrar, srv SuiteWorkflowApiServer) {
	// If the following call panics, it indicates UnimplementedSuiteWorkflowApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SuiteWorkflowApi_ServiceDesc, srv)
}

func _SuiteWorkflowApi_SuiteWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuiteWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuiteWorkflowApiServer).SuiteWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SuiteWorkflowApi_SuiteWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuiteWorkflowApiServer).SuiteWorkflow(ctx, req.(*SuiteWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SuiteWorkflowApi_ServiceDesc is the grpc.ServiceDesc for SuiteWorkflowApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SuiteWorkflowApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.v1.workflow.SuiteWorkflowApi",
	HandlerType: (*SuiteWorkflowApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SuiteWorkflow",
			Handler:    _SuiteWorkflowApi_SuiteWorkflow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cloud/v1/workflow/test.proto",
}
