// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts,import_extension=ts"
// @generated from file cloud/v1/iam/tenant.proto (package cloud.v1.iam, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodIdempotency, MethodKind } from "@bufbuild/protobuf";
import { CreateTenantRequest, Tenant, Tenant_List, TenantId, UpdateTenantRequest } from "./tenant_pbts";

/**
 * @generated from service cloud.v1.iam.TenantService
 */
export const TenantService = {
  typeName: "cloud.v1.iam.TenantService",
  methods: {
    /**
     * @generated from rpc cloud.v1.iam.TenantService.ListMyTenants
     */
    listMyTenants: {
      name: "ListMyTenants",
      I: Empty,
      O: Tenant_List,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * @generated from rpc cloud.v1.iam.TenantService.CreateTenant
     */
    createTenant: {
      name: "CreateTenant",
      I: CreateTenantRequest,
      O: Tenant,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.Idempotent,
    },
    /**
     * @generated from rpc cloud.v1.iam.TenantService.UpdateTenant
     */
    updateTenant: {
      name: "UpdateTenant",
      I: UpdateTenantRequest,
      O: Tenant,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.Idempotent,
    },
    /**
     * @generated from rpc cloud.v1.iam.TenantService.DeleteTenant
     */
    deleteTenant: {
      name: "DeleteTenant",
      I: TenantId,
      O: Tenant,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.Idempotent,
    },
  }
} as const;

