supported_cloud: SUPPORTED_CLOUD_YANDEX
hatchet_server:
  token: "YOUR_TOKEN"
  host_port:
    host: "localhost"
    port: "7707"
suite:
  tests:
    - name: "nightly"
      description: "Nightly test suite"
      stroppy_cli:
        #      binary_path: "/stroppy/stroppy"
        version: "v2.0.0"
        workload: TPCC
        stroppy_env:
          DURATION: "60s"
          SCALE_FACTOR: "1"
          #"SCALE_FACTOR_TPCC": "1", // 16mb
          #"SCALE_FACTOR_TPCB": "1", // 68mb
          K6_OTEL_EXPORTER_TYPE: "http"
          K6_OTEL_SERVICE_NAME: "stroppy"
          K6_OTEL_SERVICE_VERSION: "v2.0.0"
          K6_OTEL_HTTP_EXPORTER_INSECURE: "false"
          K6_OTEL_HTTP_EXPORTER_ENDPOINT: ""
          K6_OTEL_HTTP_EXPORTER_URL_PATH: ""
          K6_OTEL_HEADERS: ""
      stroppy_hardware:
        cores: 2
        memory: 2
        disk: 10
      database:
        standalone:
          hardware:
            cores: 2
            memory: 2
            disk: 10
          postgres:
            version: "VERSION_17"
            storage_backend: "STORAGE_TYPE_POSTGRES"
            password: "postgres"
            username: "postgres"
            database: "postgres"
            port: 5432
            postgresql_conf:
              max_connections: "1000"
