// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: deployment/deployment.proto

package deployment

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Target int32

const (
	Target_TARGET_UNSPECIFIED  Target = 0
	Target_TARGET_DOCKER       Target = 1
	Target_TARGET_YANDEX_CLOUD Target = 2
)

// Enum value maps for Target.
var (
	Target_name = map[int32]string{
		0: "TARGET_UNSPECIFIED",
		1: "TARGET_DOCKER",
		2: "TARGET_YANDEX_CLOUD",
	}
	Target_value = map[string]int32{
		"TARGET_UNSPECIFIED":  0,
		"TARGET_DOCKER":       1,
		"TARGET_YANDEX_CLOUD": 2,
	}
)

func (x Target) Enum() *Target {
	p := new(Target)
	*p = x
	return p
}

func (x Target) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Target) Descriptor() protoreflect.EnumDescriptor {
	return file_deployment_deployment_proto_enumTypes[0].Descriptor()
}

func (Target) Type() protoreflect.EnumType {
	return &file_deployment_deployment_proto_enumTypes[0]
}

func (x Target) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Target.Descriptor instead.
func (Target) EnumDescriptor() ([]byte, []int) {
	return file_deployment_deployment_proto_rawDescGZIP(), []int{0}
}

type VmUser struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Groups            []string               `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	SshAuthorizedKeys []string               `protobuf:"bytes,3,rep,name=ssh_authorized_keys,json=sshAuthorizedKeys,proto3" json:"ssh_authorized_keys,omitempty"`
	SudoRules         string                 `protobuf:"bytes,4,opt,name=sudo_rules,json=sudoRules,proto3" json:"sudo_rules,omitempty"`
	Shell             string                 `protobuf:"bytes,5,opt,name=shell,proto3" json:"shell,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VmUser) Reset() {
	*x = VmUser{}
	mi := &file_deployment_deployment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmUser) ProtoMessage() {}

func (x *VmUser) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_deployment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmUser.ProtoReflect.Descriptor instead.
func (*VmUser) Descriptor() ([]byte, []int) {
	return file_deployment_deployment_proto_rawDescGZIP(), []int{0}
}

func (x *VmUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VmUser) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *VmUser) GetSshAuthorizedKeys() []string {
	if x != nil {
		return x.SshAuthorizedKeys
	}
	return nil
}

func (x *VmUser) GetSudoRules() string {
	if x != nil {
		return x.SudoRules
	}
	return ""
}

func (x *VmUser) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

type Hardware struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cores         uint32                 `protobuf:"varint,1,opt,name=cores,proto3" json:"cores,omitempty"`   // in cores
	Memory        uint32                 `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"` // in GB
	Disk          uint32                 `protobuf:"varint,3,opt,name=disk,proto3" json:"disk,omitempty"`     // in GB
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hardware) Reset() {
	*x = Hardware{}
	mi := &file_deployment_deployment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hardware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hardware) ProtoMessage() {}

func (x *Hardware) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_deployment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hardware.ProtoReflect.Descriptor instead.
func (*Hardware) Descriptor() ([]byte, []int) {
	return file_deployment_deployment_proto_rawDescGZIP(), []int{1}
}

func (x *Hardware) GetCores() uint32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *Hardware) GetMemory() uint32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Hardware) GetDisk() uint32 {
	if x != nil {
		return x.Disk
	}
	return 0
}

type Ip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ip) Reset() {
	*x = Ip{}
	mi := &file_deployment_deployment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ip) ProtoMessage() {}

func (x *Ip) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_deployment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ip.ProtoReflect.Descriptor instead.
func (*Ip) Descriptor() ([]byte, []int) {
	return file_deployment_deployment_proto_rawDescGZIP(), []int{2}
}

func (x *Ip) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Cidr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cidr) Reset() {
	*x = Cidr{}
	mi := &file_deployment_deployment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cidr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cidr) ProtoMessage() {}

func (x *Cidr) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_deployment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cidr.ProtoReflect.Descriptor instead.
func (*Cidr) Descriptor() ([]byte, []int) {
	return file_deployment_deployment_proto_rawDescGZIP(), []int{3}
}

func (x *Cidr) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CloudInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Env           map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudInit) Reset() {
	*x = CloudInit{}
	mi := &file_deployment_deployment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudInit) ProtoMessage() {}

func (x *CloudInit) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_deployment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudInit.ProtoReflect.Descriptor instead.
func (*CloudInit) Descriptor() ([]byte, []int) {
	return file_deployment_deployment_proto_rawDescGZIP(), []int{4}
}

func (x *CloudInit) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CloudInit) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type Identifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // always unique
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // human-readable name
	Target        Target                 `protobuf:"varint,3,opt,name=target,proto3,enum=deployment.Target" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identifier) Reset() {
	*x = Identifier{}
	mi := &file_deployment_deployment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier) ProtoMessage() {}

func (x *Identifier) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_deployment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier.ProtoReflect.Descriptor instead.
func (*Identifier) Descriptor() ([]byte, []int) {
	return file_deployment_deployment_proto_rawDescGZIP(), []int{5}
}

func (x *Identifier) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Identifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Identifier) GetTarget() Target {
	if x != nil {
		return x.Target
	}
	return Target_TARGET_UNSPECIFIED
}

type Vm struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Template           *Vm_Template           `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	AssignedInternalIp *Ip                    `protobuf:"bytes,2,opt,name=assigned_internal_ip,json=assignedInternalIp,proto3" json:"assigned_internal_ip,omitempty"`
	AssignedExternalIp *Ip                    `protobuf:"bytes,3,opt,name=assigned_external_ip,json=assignedExternalIp,proto3,oneof" json:"assigned_external_ip,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Vm) Reset() {
	*x = Vm{}
	mi := &file_deployment_deployment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vm) ProtoMessage() {}

func (x *Vm) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_deployment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vm.ProtoReflect.Descriptor instead.
func (*Vm) Descriptor() ([]byte, []int) {
	return file_deployment_deployment_proto_rawDescGZIP(), []int{6}
}

func (x *Vm) GetTemplate() *Vm_Template {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *Vm) GetAssignedInternalIp() *Ip {
	if x != nil {
		return x.AssignedInternalIp
	}
	return nil
}

func (x *Vm) GetAssignedExternalIp() *Ip {
	if x != nil {
		return x.AssignedExternalIp
	}
	return nil
}

type Network struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *Identifier            `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Cidr          *Cidr                  `protobuf:"bytes,2,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Ips           []*Ip                  `protobuf:"bytes,3,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_deployment_deployment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_deployment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_deployment_deployment_proto_rawDescGZIP(), []int{7}
}

func (x *Network) GetIdentifier() *Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *Network) GetCidr() *Cidr {
	if x != nil {
		return x.Cidr
	}
	return nil
}

func (x *Network) GetIps() []*Ip {
	if x != nil {
		return x.Ips
	}
	return nil
}

type Deployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *Deployment_Template   `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	Vms           []*Vm                  `protobuf:"bytes,3,rep,name=vms,proto3" json:"vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_deployment_deployment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_deployment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_deployment_deployment_proto_rawDescGZIP(), []int{8}
}

func (x *Deployment) GetTemplate() *Deployment_Template {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *Deployment) GetVms() []*Vm {
	if x != nil {
		return x.Vms
	}
	return nil
}

type Vm_Template struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *Identifier            `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Hardware      *Hardware              `protobuf:"bytes,2,opt,name=hardware,proto3" json:"hardware,omitempty"`
	BaseImageId   string                 `protobuf:"bytes,3,opt,name=base_image_id,json=baseImageId,proto3" json:"base_image_id,omitempty"`
	HasPublicIp   bool                   `protobuf:"varint,4,opt,name=has_public_ip,json=hasPublicIp,proto3" json:"has_public_ip,omitempty"`
	VmUser        *VmUser                `protobuf:"bytes,5,opt,name=vm_user,json=vmUser,proto3" json:"vm_user,omitempty"`
	InternalIp    *Ip                    `protobuf:"bytes,6,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	CloudInit     *CloudInit             `protobuf:"bytes,7,opt,name=cloud_init,json=cloudInit,proto3" json:"cloud_init,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vm_Template) Reset() {
	*x = Vm_Template{}
	mi := &file_deployment_deployment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vm_Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vm_Template) ProtoMessage() {}

func (x *Vm_Template) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_deployment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vm_Template.ProtoReflect.Descriptor instead.
func (*Vm_Template) Descriptor() ([]byte, []int) {
	return file_deployment_deployment_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Vm_Template) GetIdentifier() *Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *Vm_Template) GetHardware() *Hardware {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *Vm_Template) GetBaseImageId() string {
	if x != nil {
		return x.BaseImageId
	}
	return ""
}

func (x *Vm_Template) GetHasPublicIp() bool {
	if x != nil {
		return x.HasPublicIp
	}
	return false
}

func (x *Vm_Template) GetVmUser() *VmUser {
	if x != nil {
		return x.VmUser
	}
	return nil
}

func (x *Vm_Template) GetInternalIp() *Ip {
	if x != nil {
		return x.InternalIp
	}
	return nil
}

func (x *Vm_Template) GetCloudInit() *CloudInit {
	if x != nil {
		return x.CloudInit
	}
	return nil
}

func (x *Vm_Template) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Deployment_Template struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *Identifier            `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Network       *Network               `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	VmTemplates   []*Vm_Template         `protobuf:"bytes,4,rep,name=vm_templates,json=vmTemplates,proto3" json:"vm_templates,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment_Template) Reset() {
	*x = Deployment_Template{}
	mi := &file_deployment_deployment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment_Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment_Template) ProtoMessage() {}

func (x *Deployment_Template) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_deployment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment_Template.ProtoReflect.Descriptor instead.
func (*Deployment_Template) Descriptor() ([]byte, []int) {
	return file_deployment_deployment_proto_rawDescGZIP(), []int{8, 0}
}

func (x *Deployment_Template) GetIdentifier() *Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *Deployment_Template) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *Deployment_Template) GetVmTemplates() []*Vm_Template {
	if x != nil {
		return x.VmTemplates
	}
	return nil
}

func (x *Deployment_Template) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_deployment_deployment_proto protoreflect.FileDescriptor

const file_deployment_deployment_proto_rawDesc = "" +
	"\n" +
	"\x1bdeployment/deployment.proto\x12\n" +
	"deployment\x1a\x17validate/validate.proto\"\xc8\x01\n" +
	"\x06VmUser\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12 \n" +
	"\x06groups\x18\x02 \x03(\tB\b\xfaB\x05\x92\x01\x02\b\x01R\x06groups\x128\n" +
	"\x13ssh_authorized_keys\x18\x03 \x03(\tB\b\xfaB\x05\x92\x01\x02\b\x01R\x11sshAuthorizedKeys\x12&\n" +
	"\n" +
	"sudo_rules\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tsudoRules\x12\x1d\n" +
	"\x05shell\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05shell\"L\n" +
	"\bHardware\x12\x14\n" +
	"\x05cores\x18\x01 \x01(\rR\x05cores\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\rR\x06memory\x12\x12\n" +
	"\x04disk\x18\x03 \x01(\rR\x04disk\"#\n" +
	"\x02Ip\x12\x1d\n" +
	"\x05value\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05value\"%\n" +
	"\x04Cidr\x12\x1d\n" +
	"\x05value\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05value\"\x98\x01\n" +
	"\tCloudInit\x12!\n" +
	"\acontent\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\acontent\x120\n" +
	"\x03env\x18\x02 \x03(\v2\x1e.deployment.CloudInit.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"x\n" +
	"\n" +
	"Identifier\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x124\n" +
	"\x06target\x18\x03 \x01(\x0e2\x12.deployment.TargetB\b\xfaB\x05\x82\x01\x02\x10\x01R\x06target\"\xeb\x05\n" +
	"\x02Vm\x12=\n" +
	"\btemplate\x18\x01 \x01(\v2\x17.deployment.Vm.TemplateB\b\xfaB\x05\x8a\x01\x02\x10\x01R\btemplate\x12J\n" +
	"\x14assigned_internal_ip\x18\x02 \x01(\v2\x0e.deployment.IpB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x12assignedInternalIp\x12E\n" +
	"\x14assigned_external_ip\x18\x03 \x01(\v2\x0e.deployment.IpH\x00R\x12assignedExternalIp\x88\x01\x01\x1a\xf9\x03\n" +
	"\bTemplate\x12@\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x16.deployment.IdentifierB\b\xfaB\x05\x8a\x01\x02\x10\x01R\n" +
	"identifier\x12:\n" +
	"\bhardware\x18\x02 \x01(\v2\x14.deployment.HardwareB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bhardware\x12+\n" +
	"\rbase_image_id\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vbaseImageId\x12\"\n" +
	"\rhas_public_ip\x18\x04 \x01(\bR\vhasPublicIp\x12+\n" +
	"\avm_user\x18\x05 \x01(\v2\x12.deployment.VmUserR\x06vmUser\x129\n" +
	"\vinternal_ip\x18\x06 \x01(\v2\x0e.deployment.IpB\b\xfaB\x05\x8a\x01\x02\x10\x01R\n" +
	"internalIp\x12>\n" +
	"\n" +
	"cloud_init\x18\a \x01(\v2\x15.deployment.CloudInitB\b\xfaB\x05\x8a\x01\x02\x10\x01R\tcloudInit\x12;\n" +
	"\x06labels\x18\b \x03(\v2#.deployment.Vm.Template.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x17\n" +
	"\x15_assigned_external_ip\"\xa7\x01\n" +
	"\aNetwork\x12@\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x16.deployment.IdentifierB\b\xfaB\x05\x8a\x01\x02\x10\x01R\n" +
	"identifier\x12.\n" +
	"\x04cidr\x18\x02 \x01(\v2\x10.deployment.CidrB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x04cidr\x12*\n" +
	"\x03ips\x18\x03 \x03(\v2\x0e.deployment.IpB\b\xfaB\x05\x92\x01\x02\b\x01R\x03ips\"\xd5\x03\n" +
	"\n" +
	"Deployment\x12E\n" +
	"\btemplate\x18\x01 \x01(\v2\x1f.deployment.Deployment.TemplateB\b\xfaB\x05\x8a\x01\x02\x10\x01R\btemplate\x12*\n" +
	"\x03vms\x18\x03 \x03(\v2\x0e.deployment.VmB\b\xfaB\x05\x92\x01\x02\b\x01R\x03vms\x1a\xd3\x02\n" +
	"\bTemplate\x12@\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x16.deployment.IdentifierB\b\xfaB\x05\x8a\x01\x02\x10\x01R\n" +
	"identifier\x127\n" +
	"\anetwork\x18\x03 \x01(\v2\x13.deployment.NetworkB\b\xfaB\x05\x8a\x01\x02\x10\x01R\anetwork\x12D\n" +
	"\fvm_templates\x18\x04 \x03(\v2\x17.deployment.Vm.TemplateB\b\xfaB\x05\x92\x01\x02\b\x01R\vvmTemplates\x12I\n" +
	"\bmetadata\x18\x05 \x03(\v2-.deployment.Deployment.Template.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*L\n" +
	"\x06Target\x12\x16\n" +
	"\x12TARGET_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rTARGET_DOCKER\x10\x01\x12\x17\n" +
	"\x13TARGET_YANDEX_CLOUD\x10\x02BBZ@github.com/stroppy-io/hatchet-workflow/internal/proto/deploymentb\x06proto3"

var (
	file_deployment_deployment_proto_rawDescOnce sync.Once
	file_deployment_deployment_proto_rawDescData []byte
)

func file_deployment_deployment_proto_rawDescGZIP() []byte {
	file_deployment_deployment_proto_rawDescOnce.Do(func() {
		file_deployment_deployment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deployment_deployment_proto_rawDesc), len(file_deployment_deployment_proto_rawDesc)))
	})
	return file_deployment_deployment_proto_rawDescData
}

var file_deployment_deployment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_deployment_deployment_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_deployment_deployment_proto_goTypes = []any{
	(Target)(0),                 // 0: deployment.Target
	(*VmUser)(nil),              // 1: deployment.VmUser
	(*Hardware)(nil),            // 2: deployment.Hardware
	(*Ip)(nil),                  // 3: deployment.Ip
	(*Cidr)(nil),                // 4: deployment.Cidr
	(*CloudInit)(nil),           // 5: deployment.CloudInit
	(*Identifier)(nil),          // 6: deployment.Identifier
	(*Vm)(nil),                  // 7: deployment.Vm
	(*Network)(nil),             // 8: deployment.Network
	(*Deployment)(nil),          // 9: deployment.Deployment
	nil,                         // 10: deployment.CloudInit.EnvEntry
	(*Vm_Template)(nil),         // 11: deployment.Vm.Template
	nil,                         // 12: deployment.Vm.Template.LabelsEntry
	(*Deployment_Template)(nil), // 13: deployment.Deployment.Template
	nil,                         // 14: deployment.Deployment.Template.MetadataEntry
}
var file_deployment_deployment_proto_depIdxs = []int32{
	10, // 0: deployment.CloudInit.env:type_name -> deployment.CloudInit.EnvEntry
	0,  // 1: deployment.Identifier.target:type_name -> deployment.Target
	11, // 2: deployment.Vm.template:type_name -> deployment.Vm.Template
	3,  // 3: deployment.Vm.assigned_internal_ip:type_name -> deployment.Ip
	3,  // 4: deployment.Vm.assigned_external_ip:type_name -> deployment.Ip
	6,  // 5: deployment.Network.identifier:type_name -> deployment.Identifier
	4,  // 6: deployment.Network.cidr:type_name -> deployment.Cidr
	3,  // 7: deployment.Network.ips:type_name -> deployment.Ip
	13, // 8: deployment.Deployment.template:type_name -> deployment.Deployment.Template
	7,  // 9: deployment.Deployment.vms:type_name -> deployment.Vm
	6,  // 10: deployment.Vm.Template.identifier:type_name -> deployment.Identifier
	2,  // 11: deployment.Vm.Template.hardware:type_name -> deployment.Hardware
	1,  // 12: deployment.Vm.Template.vm_user:type_name -> deployment.VmUser
	3,  // 13: deployment.Vm.Template.internal_ip:type_name -> deployment.Ip
	5,  // 14: deployment.Vm.Template.cloud_init:type_name -> deployment.CloudInit
	12, // 15: deployment.Vm.Template.labels:type_name -> deployment.Vm.Template.LabelsEntry
	6,  // 16: deployment.Deployment.Template.identifier:type_name -> deployment.Identifier
	8,  // 17: deployment.Deployment.Template.network:type_name -> deployment.Network
	11, // 18: deployment.Deployment.Template.vm_templates:type_name -> deployment.Vm.Template
	14, // 19: deployment.Deployment.Template.metadata:type_name -> deployment.Deployment.Template.MetadataEntry
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_deployment_deployment_proto_init() }
func file_deployment_deployment_proto_init() {
	if File_deployment_deployment_proto != nil {
		return
	}
	file_deployment_deployment_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deployment_deployment_proto_rawDesc), len(file_deployment_deployment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_deployment_deployment_proto_goTypes,
		DependencyIndexes: file_deployment_deployment_proto_depIdxs,
		EnumInfos:         file_deployment_deployment_proto_enumTypes,
		MessageInfos:      file_deployment_deployment_proto_msgTypes,
	}.Build()
	File_deployment_deployment_proto = out.File
	file_deployment_deployment_proto_goTypes = nil
	file_deployment_deployment_proto_depIdxs = nil
}
