// @generated by protoc-gen-es v2.11.0 with parameter "import_extension=ts,json_types=true,target=ts,valid_types=legacy_required+protovalidate_required"
// @generated from file cloud/v1/common/tags.proto (package cloud.v1.common, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cloud/v1/common/tags.proto.
 */
export const file_cloud_v1_common_tags: GenFile = /*@__PURE__*/
  fileDesc("ChpjbG91ZC92MS9jb21tb24vdGFncy5wcm90bxIPY2xvdWQudjEuY29tbW9uInYKBFRhZ3MSDAoEdGFncxgBIAMoCRIxCgZsYWJlbHMYAiADKAsyIS5jbG91ZC52MS5jb21tb24uVGFncy5MYWJlbHNFbnRyeRotCgtMYWJlbHNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBQkRaQmdpdGh1Yi5jb20vc3Ryb3BweS1pby9zdHJvcHB5LWNsb3VkL2ludGVybmFsL3Byb3RvL2Nsb3VkL3YxL2NvbW1vbmIGcHJvdG8z");

/**
 * @generated from message cloud.v1.common.Tags
 */
export type Tags = Message<"cloud.v1.common.Tags"> & {
  /**
   * tags is a flat label set.
   *
   * @generated from field: repeated string tags = 1;
   */
  tags: string[];

  /**
   * labels is arbitrary key/value metadata (reconcile/observability) — free to
   * extend since Tags is always serialized as a single column.
   *
   * @generated from field: map<string, string> labels = 2;
   */
  labels: { [key: string]: string };
};

/**
 * @generated from message cloud.v1.common.Tags
 */
export type TagsJson = {
  /**
   * tags is a flat label set.
   *
   * @generated from field: repeated string tags = 1;
   */
  tags?: string[];

  /**
   * labels is arbitrary key/value metadata (reconcile/observability) — free to
   * extend since Tags is always serialized as a single column.
   *
   * @generated from field: map<string, string> labels = 2;
   */
  labels?: { [key: string]: string };
};

export type TagsValid = Tags;

/**
 * Describes the message cloud.v1.common.Tags.
 * Use `create(TagsSchema)` to create a new message.
 */
export const TagsSchema: GenMessage<Tags, {jsonType: TagsJson, validType: TagsValid}> = /*@__PURE__*/
  messageDesc(file_cloud_v1_common_tags, 0);

