syntax = "proto3";

package cloud.v1.domain;

import "cloud/v1/deployment/deployment.proto";
import "cloud/v1/domain/database.proto";
import "cloud/v1/domain/workload.proto";
import "cloud/v1/domain/topology.proto";
import "cloud/v1/runtime/primitive/dag.proto";
import "validate/validate.proto";

option go_package = "github.com/stroppy-io/stroppy-cloud/internal/proto/cloud/v1/domain";

message TestPreset {
    domain.Database database = 1 [(validate.rules).message.required = true];
    domain.Workload workload = 2 [(validate.rules).message.required = true];
    /* Merged topology from database and workload */
    domain.Topology topology = 3 [(validate.rules).message.required = true];
    /* Materialized from topology */
    deployment.DeploymentIntent deployment = 4 [(validate.rules).message.required = true];
}