// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: cloud/v1/models/apitoken.proto

package models

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ApiToken with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ApiToken) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ApiToken with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ApiTokenMultiError, or nil
// if none found.
func (m *ApiToken) ValidateAll() error {
	return m.validate(true)
}

func (m *ApiToken) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetEntity()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ApiTokenValidationError{
					field:  "Entity",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ApiTokenValidationError{
					field:  "Entity",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEntity()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ApiTokenValidationError{
				field:  "Entity",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetOwned()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ApiTokenValidationError{
					field:  "Owned",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ApiTokenValidationError{
					field:  "Owned",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOwned()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ApiTokenValidationError{
				field:  "Owned",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 255 {
		err := ApiTokenValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _ApiToken_Role_NotInLookup[m.GetRole()]; ok {
		err := ApiTokenValidationError{
			field:  "Role",
			reason: "value must not be in list [ROLE_UNSPECIFIED ROLE_OWNER]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := TenantMember_Role_name[int32(m.GetRole())]; !ok {
		err := ApiTokenValidationError{
			field:  "Role",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.ExpiresAt != nil {

		if all {
			switch v := interface{}(m.GetExpiresAt()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ApiTokenValidationError{
						field:  "ExpiresAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ApiTokenValidationError{
						field:  "ExpiresAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetExpiresAt()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ApiTokenValidationError{
					field:  "ExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ApiTokenMultiError(errors)
	}

	return nil
}

// ApiTokenMultiError is an error wrapping multiple validation errors returned
// by ApiToken.ValidateAll() if the designated constraints aren't met.
type ApiTokenMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ApiTokenMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ApiTokenMultiError) AllErrors() []error { return m }

// ApiTokenValidationError is the validation error returned by
// ApiToken.Validate if the designated constraints aren't met.
type ApiTokenValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ApiTokenValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ApiTokenValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ApiTokenValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ApiTokenValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ApiTokenValidationError) ErrorName() string { return "ApiTokenValidationError" }

// Error satisfies the builtin error interface
func (e ApiTokenValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sApiToken.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ApiTokenValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ApiTokenValidationError{}

var _ApiToken_Role_NotInLookup = map[TenantMember_Role]struct{}{
	0: {},
	3: {},
}

// Validate checks the field values on ApiToken_List with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ApiToken_List) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ApiToken_List with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ApiToken_ListMultiError, or
// nil if none found.
func (m *ApiToken_List) ValidateAll() error {
	return m.validate(true)
}

func (m *ApiToken_List) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetApiTokens() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ApiToken_ListValidationError{
						field:  fmt.Sprintf("ApiTokens[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ApiToken_ListValidationError{
						field:  fmt.Sprintf("ApiTokens[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ApiToken_ListValidationError{
					field:  fmt.Sprintf("ApiTokens[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ApiToken_ListMultiError(errors)
	}

	return nil
}

// ApiToken_ListMultiError is an error wrapping multiple validation errors
// returned by ApiToken_List.ValidateAll() if the designated constraints
// aren't met.
type ApiToken_ListMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ApiToken_ListMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ApiToken_ListMultiError) AllErrors() []error { return m }

// ApiToken_ListValidationError is the validation error returned by
// ApiToken_List.Validate if the designated constraints aren't met.
type ApiToken_ListValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ApiToken_ListValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ApiToken_ListValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ApiToken_ListValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ApiToken_ListValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ApiToken_ListValidationError) ErrorName() string { return "ApiToken_ListValidationError" }

// Error satisfies the builtin error interface
func (e ApiToken_ListValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sApiToken_List.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ApiToken_ListValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ApiToken_ListValidationError{}
