// Code generated by protoc-gen-go-plain. DO NOT EDIT.
// source: cloud/v1/models/database_preset.proto

package models

import (
	deployment "github.com/stroppy-io/stroppy-cloud/internal/proto/cloud/v1/deployment"
	domain "github.com/stroppy-io/stroppy-cloud/internal/proto/cloud/v1/domain"
	render "github.com/stroppy-io/stroppy-cloud/internal/proto/cloud/v1/runtime/render"
	ratelcast "github.com/yaroher/ratel/pkg/ratelcast"
	time "time"
)

type DatabasePresetScanner struct {
	Id               string                       `json:"id"` // origin: embed, empath: id
	CreatedAt        time.Time                    `json:"createdAt"`
	UpdatedAt        time.Time                    `json:"updatedAt"`
	OwnerAccountId   string                       `json:"ownerAccountId"` // origin: type_alias, empath: owner_account_id
	Kind             string                       `json:"kind"`
	Version          string                       `json:"version"`
	Config           *render.Config               `json:"config"`
	Target           *domain.Database_Target      `json:"target"`
	Options          *domain.Database_Options     `json:"options"`
	DeploymentIntent *deployment.DeploymentIntent `json:"deploymentIntent,omitempty"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *DatabasePreset) IntoPlain() *DatabasePresetScanner {
	if pb == nil {
		return nil
	}
	p := &DatabasePresetScanner{}

	// Id from id
	if pb.GetEntity() != nil && pb.GetEntity().GetId() != nil {
		p.Id = pb.GetEntity().GetId().GetValue()
	}
	// CreatedAt from
	if pb.GetEntity() != nil && pb.GetEntity().GetTimestamps() != nil && pb.GetEntity().GetTimestamps().GetCreatedAt() != nil {
		p.CreatedAt = ratelcast.TimestampToTime(pb.GetEntity().GetTimestamps().GetCreatedAt())
	}
	// UpdatedAt from
	if pb.GetEntity() != nil && pb.GetEntity().GetTimestamps() != nil && pb.GetEntity().GetTimestamps().GetUpdatedAt() != nil {
		p.UpdatedAt = ratelcast.TimestampToTime(pb.GetEntity().GetTimestamps().GetUpdatedAt())
	}
	// OwnerAccountId type alias from owner_account_id
	if pb.GetOwnerAccountId() != nil {
		p.OwnerAccountId = pb.GetOwnerAccountId().GetValue()
	}
	// Kind from
	if pb.GetDatabase() != nil {
		p.Kind = pb.GetDatabase().GetKind().String()
	}
	// Version from
	if pb.GetDatabase() != nil {
		p.Version = pb.GetDatabase().GetVersion()
	}
	// Config from
	if pb.GetDatabase() != nil && pb.GetDatabase().GetConfig() != nil {
		p.Config = pb.GetDatabase().GetConfig()
	}
	// Target from
	if pb.GetDatabase() != nil && pb.GetDatabase().GetTarget() != nil {
		p.Target = pb.GetDatabase().GetTarget()
	}
	// Options from
	if pb.GetDatabase() != nil && pb.GetDatabase().GetOptions() != nil {
		p.Options = pb.GetDatabase().GetOptions()
	}
	// DeploymentIntent from
	if pb.GetDatabase() != nil && pb.GetDatabase().GetDeploymentIntent() != nil {
		p.DeploymentIntent = pb.GetDatabase().GetDeploymentIntent()
	}
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *DatabasePresetScanner) IntoPb() *DatabasePreset {
	if p == nil {
		return nil
	}
	pb := &DatabasePreset{}

	// Id -> id
	if p.Id != "" {
		if pb.Entity == nil {
			pb.Entity = &Entity{}
		}
		if pb.Entity.Id == nil {
			pb.Entity.Id = &Ulid{}
		}
		pb.Entity.Id.Value = p.Id
	}
	// CreatedAt ->
	if pb.Entity == nil {
		pb.Entity = &Entity{}
	}
	if pb.Entity.Timestamps == nil {
		pb.Entity.Timestamps = &Timestamps{}
	}
	pb.Entity.Timestamps.CreatedAt = ratelcast.TimeToTimestamp(p.CreatedAt)
	// UpdatedAt ->
	if pb.Entity == nil {
		pb.Entity = &Entity{}
	}
	if pb.Entity.Timestamps == nil {
		pb.Entity.Timestamps = &Timestamps{}
	}
	pb.Entity.Timestamps.UpdatedAt = ratelcast.TimeToTimestamp(p.UpdatedAt)
	// OwnerAccountId type alias -> owner_account_id
	if p.OwnerAccountId != "" {
		pb.OwnerAccountId = &AccountId{Value: p.OwnerAccountId}
	}
	// Kind ->
	if p.Kind != "" {
		if pb.Database == nil {
			pb.Database = &domain.Database{}
		}
		pb.Database.Kind = p.Kind
	}
	// Version ->
	if p.Version != "" {
		if pb.Database == nil {
			pb.Database = &domain.Database{}
		}
		pb.Database.Version = p.Version
	}
	// Config ->
	if p.Config != nil {
		if pb.Database == nil {
			pb.Database = &domain.Database{}
		}
		pb.Database.Config = p.Config
	}
	// Target ->
	if p.Target != nil {
		if pb.Database == nil {
			pb.Database = &domain.Database{}
		}
		pb.Database.Target = p.Target
	}
	// Options ->
	if p.Options != nil {
		if pb.Database == nil {
			pb.Database = &domain.Database{}
		}
		pb.Database.Options = p.Options
	}
	// DeploymentIntent ->
	if p.DeploymentIntent != nil {
		if pb.Database == nil {
			pb.Database = &domain.Database{}
		}
		pb.Database.DeploymentIntent = p.DeploymentIntent
	}
	return pb
}
