// Code generated by protoc-gen-go-jx. DO NOT EDIT.

package iam

import (
	fmt "fmt"
	jx "github.com/go-faster/jx"
	jxpb "github.com/gopherex/protoc-gen-go-jx/jxpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (m *Account) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.Id != "" {
		e.FieldStart("id")
		e.Str(m.Id)
	}
	if m.Email != "" {
		e.FieldStart("email")
		e.Str(m.Email)
	}
	if m.EmailVerified != false {
		e.FieldStart("emailVerified")
		e.Bool(m.EmailVerified)
	}
	if m.Nickname != "" {
		e.FieldStart("nickname")
		e.Str(m.Nickname)
	}
	if m.IsAdmin != false {
		e.FieldStart("isAdmin")
		e.Bool(m.IsAdmin)
	}
	if m.CreatedAt != nil {
		e.FieldStart("createdAt")
		jxpb.EncTimestamp(e, m.CreatedAt)
	}
	if m.UpdatedAt != nil {
		e.FieldStart("updatedAt")
		jxpb.EncTimestamp(e, m.UpdatedAt)
	}
	e.ObjEnd()
}

func (m *Account) Decode(d *jx.Decoder) error {
	seen := map[string]bool{}
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "id":
			if seen["Id"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Id"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.Id = v
			return nil
		case "email":
			if seen["Email"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Email"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.Email = v
			return nil
		case "emailVerified", "email_verified":
			if seen["EmailVerified"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["EmailVerified"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Bool()
			if err != nil {
				return err
			}
			m.EmailVerified = v
			return nil
		case "nickname":
			if seen["Nickname"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Nickname"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.Nickname = v
			return nil
		case "isAdmin", "is_admin":
			if seen["IsAdmin"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["IsAdmin"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Bool()
			if err != nil {
				return err
			}
			m.IsAdmin = v
			return nil
		case "createdAt", "created_at":
			if seen["CreatedAt"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["CreatedAt"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.CreatedAt = &timestamppb.Timestamp{}
			if err := jxpb.DecTimestamp(d, m.CreatedAt); err != nil {
				return err
			}
			return nil
		case "updatedAt", "updated_at":
			if seen["UpdatedAt"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["UpdatedAt"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.UpdatedAt = &timestamppb.Timestamp{}
			if err := jxpb.DecTimestamp(d, m.UpdatedAt); err != nil {
				return err
			}
			return nil
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *Account) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *Account) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}
