// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cloud/v1/iam/api_token.proto

package iam

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	common "github.com/stroppy-io/stroppy-cloud/internal/proto/cloud/v1/common"
	_ "github.com/yaroher/protoc-gen-go-plain/goplain"
	_ "github.com/yaroher/ratel/ratelproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ApiTokenScope — granular permission for an API token.
type ApiTokenScope int32

const (
	ApiTokenScope_API_TOKEN_SCOPE_UNSPECIFIED    ApiTokenScope = 0
	ApiTokenScope_API_TOKEN_SCOPE_RUNS_READ      ApiTokenScope = 1
	ApiTokenScope_API_TOKEN_SCOPE_RUNS_WRITE     ApiTokenScope = 2
	ApiTokenScope_API_TOKEN_SCOPE_PRESETS_READ   ApiTokenScope = 3
	ApiTokenScope_API_TOKEN_SCOPE_PRESETS_WRITE  ApiTokenScope = 4
	ApiTokenScope_API_TOKEN_SCOPE_SETTINGS_READ  ApiTokenScope = 5
	ApiTokenScope_API_TOKEN_SCOPE_SETTINGS_WRITE ApiTokenScope = 6
	ApiTokenScope_API_TOKEN_SCOPE_ADMIN          ApiTokenScope = 99
)

// Enum value maps for ApiTokenScope.
var (
	ApiTokenScope_name = map[int32]string{
		0:  "API_TOKEN_SCOPE_UNSPECIFIED",
		1:  "API_TOKEN_SCOPE_RUNS_READ",
		2:  "API_TOKEN_SCOPE_RUNS_WRITE",
		3:  "API_TOKEN_SCOPE_PRESETS_READ",
		4:  "API_TOKEN_SCOPE_PRESETS_WRITE",
		5:  "API_TOKEN_SCOPE_SETTINGS_READ",
		6:  "API_TOKEN_SCOPE_SETTINGS_WRITE",
		99: "API_TOKEN_SCOPE_ADMIN",
	}
	ApiTokenScope_value = map[string]int32{
		"API_TOKEN_SCOPE_UNSPECIFIED":    0,
		"API_TOKEN_SCOPE_RUNS_READ":      1,
		"API_TOKEN_SCOPE_RUNS_WRITE":     2,
		"API_TOKEN_SCOPE_PRESETS_READ":   3,
		"API_TOKEN_SCOPE_PRESETS_WRITE":  4,
		"API_TOKEN_SCOPE_SETTINGS_READ":  5,
		"API_TOKEN_SCOPE_SETTINGS_WRITE": 6,
		"API_TOKEN_SCOPE_ADMIN":          99,
	}
)

func (x ApiTokenScope) Enum() *ApiTokenScope {
	p := new(ApiTokenScope)
	*p = x
	return p
}

func (x ApiTokenScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiTokenScope) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_v1_iam_api_token_proto_enumTypes[0].Descriptor()
}

func (ApiTokenScope) Type() protoreflect.EnumType {
	return &file_cloud_v1_iam_api_token_proto_enumTypes[0]
}

func (x ApiTokenScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiTokenScope.Descriptor instead.
func (ApiTokenScope) EnumDescriptor() ([]byte, []int) {
	return file_cloud_v1_iam_api_token_proto_rawDescGZIP(), []int{0}
}

type ApiTokenId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiTokenId) Reset() {
	*x = ApiTokenId{}
	mi := &file_cloud_v1_iam_api_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiTokenId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiTokenId) ProtoMessage() {}

func (x *ApiTokenId) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_iam_api_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiTokenId.ProtoReflect.Descriptor instead.
func (*ApiTokenId) Descriptor() ([]byte, []int) {
	return file_cloud_v1_iam_api_token_proto_rawDescGZIP(), []int{0}
}

func (x *ApiTokenId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// ApiToken — long-lived bearer token for tenant-scoped automation (CI/CD,
// scripts). Token value is shown only once at creation; storage keeps the
// SHA-256 hash. Scopes restrict the permitted operations.
type ApiToken struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       *ApiTokenId            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId *TenantId              `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// created_by — user who issued the token; SET_NULL on user removal so
	// token survives audit but loses attribution.
	CreatedBy  *UserId            `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3,oneof" json:"created_by,omitempty"`
	Timestamps *common.Timestamps `protobuf:"bytes,4,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	// Human-readable label shown in the UI ("ci-deploy-prod", "github-actions").
	Name          string                 `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,11,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Scopes        []ApiTokenScope        `protobuf:"varint,20,rep,packed,name=scopes,proto3,enum=cloud.v1.iam.ApiTokenScope" json:"scopes,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=last_used_at,json=lastUsedAt,proto3,oneof" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiToken) Reset() {
	*x = ApiToken{}
	mi := &file_cloud_v1_iam_api_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiToken) ProtoMessage() {}

func (x *ApiToken) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_iam_api_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiToken.ProtoReflect.Descriptor instead.
func (*ApiToken) Descriptor() ([]byte, []int) {
	return file_cloud_v1_iam_api_token_proto_rawDescGZIP(), []int{1}
}

func (x *ApiToken) GetId() *ApiTokenId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ApiToken) GetTenantId() *TenantId {
	if x != nil {
		return x.TenantId
	}
	return nil
}

func (x *ApiToken) GetCreatedBy() *UserId {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *ApiToken) GetTimestamps() *common.Timestamps {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

func (x *ApiToken) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiToken) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ApiToken) GetScopes() []ApiTokenScope {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ApiToken) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ApiToken) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type CreateApiTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *ApiToken              `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApiTokenRequest) Reset() {
	*x = CreateApiTokenRequest{}
	mi := &file_cloud_v1_iam_api_token_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiTokenRequest) ProtoMessage() {}

func (x *CreateApiTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_iam_api_token_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateApiTokenRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_iam_api_token_proto_rawDescGZIP(), []int{2}
}

func (x *CreateApiTokenRequest) GetToken() *ApiToken {
	if x != nil {
		return x.Token
	}
	return nil
}

// CreateApiTokenResponse — returned ONCE at creation with the raw token.
type CreateApiTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Token *ApiToken              `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// raw_token — full bearer string. Server stores only SHA-256 hash.
	// Caller must persist this value; never shown again.
	RawToken      string `protobuf:"bytes,2,opt,name=raw_token,json=rawToken,proto3" json:"raw_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApiTokenResponse) Reset() {
	*x = CreateApiTokenResponse{}
	mi := &file_cloud_v1_iam_api_token_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiTokenResponse) ProtoMessage() {}

func (x *CreateApiTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_iam_api_token_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateApiTokenResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_iam_api_token_proto_rawDescGZIP(), []int{3}
}

func (x *CreateApiTokenResponse) GetToken() *ApiToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *CreateApiTokenResponse) GetRawToken() string {
	if x != nil {
		return x.RawToken
	}
	return ""
}

type UpdateApiTokenExpiryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *ApiTokenId            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApiTokenExpiryRequest) Reset() {
	*x = UpdateApiTokenExpiryRequest{}
	mi := &file_cloud_v1_iam_api_token_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApiTokenExpiryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApiTokenExpiryRequest) ProtoMessage() {}

func (x *UpdateApiTokenExpiryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_iam_api_token_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApiTokenExpiryRequest.ProtoReflect.Descriptor instead.
func (*UpdateApiTokenExpiryRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_iam_api_token_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateApiTokenExpiryRequest) GetId() *ApiTokenId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpdateApiTokenExpiryRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ApiToken_List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiTokens     []*ApiToken            `protobuf:"bytes,1,rep,name=api_tokens,json=apiTokens,proto3" json:"api_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiToken_List) Reset() {
	*x = ApiToken_List{}
	mi := &file_cloud_v1_iam_api_token_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiToken_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiToken_List) ProtoMessage() {}

func (x *ApiToken_List) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_iam_api_token_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiToken_List.ProtoReflect.Descriptor instead.
func (*ApiToken_List) Descriptor() ([]byte, []int) {
	return file_cloud_v1_iam_api_token_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ApiToken_List) GetApiTokens() []*ApiToken {
	if x != nil {
		return x.ApiTokens
	}
	return nil
}

var File_cloud_v1_iam_api_token_proto protoreflect.FileDescriptor

const file_cloud_v1_iam_api_token_proto_rawDesc = "" +
	"\n" +
	"\x1ccloud/v1/iam/api_token.proto\x12\fcloud.v1.iam\x1a cloud/v1/common/timestamps.proto\x1a\x19cloud/v1/iam/tenant.proto\x1a\x17cloud/v1/iam/user.proto\x1a\x15goplain/goplain.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bratelproto/ratelproto.proto\x1a\x17validate/validate.proto\"6\n" +
	"\n" +
	"ApiTokenId\x12\x1e\n" +
	"\x05value\x18\x01 \x01(\tB\b\xfaB\x05r\x03\x98\x01\x1aR\x05value:\b\x82\xa6\x1d\x04\b\x01\x10\x01\"\xb7\x06\n" +
	"\bApiToken\x12:\n" +
	"\x02id\x18\x01 \x01(\v2\x18.cloud.v1.iam.ApiTokenIdB\x10\xfaB\x05\x8a\x01\x02\x10\x01\x9a\xb5\x18\x04\x12\x02\x10\x01R\x02id\x12R\n" +
	"\ttenant_id\x18\x02 \x01(\v2\x16.cloud.v1.iam.TenantIdB\x1d\xfaB\x05\x8a\x01\x02\x10\x01\x9a\xb5\x18\x11\x12\x0f2\atenants:\x02id@\x01R\btenantId\x12M\n" +
	"\n" +
	"created_by\x18\x03 \x01(\v2\x14.cloud.v1.iam.UserIdB\x13\x9a\xb5\x18\x0f\x12\r2\x05users:\x02id@\x02H\x00R\tcreatedBy\x88\x01\x01\x12C\n" +
	"\n" +
	"timestamps\x18\x04 \x01(\v2\x1b.cloud.v1.common.TimestampsB\x06\x82\xa6\x1d\x02 \x01R\n" +
	"timestamps\x12\x1e\n" +
	"\x04name\x18\n" +
	" \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01R\x04name\x12/\n" +
	"\vdescription\x18\v \x01(\tB\b\xfaB\x05r\x03\x18\x80\bH\x01R\vdescription\x88\x01\x01\x12=\n" +
	"\x06scopes\x18\x14 \x03(\x0e2\x1b.cloud.v1.iam.ApiTokenScopeB\b\xfaB\x05\x92\x01\x02\b\x01R\x06scopes\x12>\n" +
	"\n" +
	"expires_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\texpiresAt\x88\x01\x01\x12A\n" +
	"\flast_used_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\n" +
	"lastUsedAt\x88\x01\x01\x1a=\n" +
	"\x04List\x125\n" +
	"\n" +
	"api_tokens\x18\x01 \x03(\v2\x16.cloud.v1.iam.ApiTokenR\tapiTokens:v\x92\xb5\x18l\b\x01\x12\n" +
	"api_tokens\x1a\x12\n" +
	"\n" +
	"token_hash\x12\x04TEXT*\"\n" +
	"\x15api_tokens_tenant_idx\x12\ttenant_id*$\n" +
	"\x14api_tokens_hash_uniq\x12\n" +
	"token_hash\x18\x01\x82\xa6\x1d\x02\b\x01B\r\n" +
	"\v_created_byB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_expires_atB\x0f\n" +
	"\r_last_used_at\"O\n" +
	"\x15CreateApiTokenRequest\x126\n" +
	"\x05token\x18\x01 \x01(\v2\x16.cloud.v1.iam.ApiTokenB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x05token\"c\n" +
	"\x16CreateApiTokenResponse\x12,\n" +
	"\x05token\x18\x01 \x01(\v2\x16.cloud.v1.iam.ApiTokenR\x05token\x12\x1b\n" +
	"\traw_token\x18\x02 \x01(\tR\brawToken\"\xa0\x01\n" +
	"\x1bUpdateApiTokenExpiryRequest\x122\n" +
	"\x02id\x18\x01 \x01(\v2\x18.cloud.v1.iam.ApiTokenIdB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x02id\x12>\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiresAt\x88\x01\x01B\r\n" +
	"\v_expires_at*\x96\x02\n" +
	"\rApiTokenScope\x12\x1f\n" +
	"\x1bAPI_TOKEN_SCOPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19API_TOKEN_SCOPE_RUNS_READ\x10\x01\x12\x1e\n" +
	"\x1aAPI_TOKEN_SCOPE_RUNS_WRITE\x10\x02\x12 \n" +
	"\x1cAPI_TOKEN_SCOPE_PRESETS_READ\x10\x03\x12!\n" +
	"\x1dAPI_TOKEN_SCOPE_PRESETS_WRITE\x10\x04\x12!\n" +
	"\x1dAPI_TOKEN_SCOPE_SETTINGS_READ\x10\x05\x12\"\n" +
	"\x1eAPI_TOKEN_SCOPE_SETTINGS_WRITE\x10\x06\x12\x19\n" +
	"\x15API_TOKEN_SCOPE_ADMIN\x10c2\xad\x03\n" +
	"\x0fApiTokenService\x12`\n" +
	"\x0eCreateApiToken\x12#.cloud.v1.iam.CreateApiTokenRequest\x1a$.cloud.v1.iam.CreateApiTokenResponse\"\x03\x90\x02\x02\x12G\n" +
	"\x0eRevokeApiToken\x12\x18.cloud.v1.iam.ApiTokenId\x1a\x16.cloud.v1.iam.ApiToken\"\x03\x90\x02\x02\x12D\n" +
	"\vGetApiToken\x12\x18.cloud.v1.iam.ApiTokenId\x1a\x16.cloud.v1.iam.ApiToken\"\x03\x90\x02\x01\x12I\n" +
	"\rListApiTokens\x12\x16.cloud.v1.iam.TenantId\x1a\x1b.cloud.v1.iam.ApiToken.List\"\x03\x90\x02\x01\x12^\n" +
	"\x14UpdateApiTokenExpiry\x12).cloud.v1.iam.UpdateApiTokenExpiryRequest\x1a\x16.cloud.v1.iam.ApiToken\"\x03\x90\x02\x02BAZ?github.com/stroppy-io/stroppy-cloud/internal/proto/cloud/v1/iamb\x06proto3"

var (
	file_cloud_v1_iam_api_token_proto_rawDescOnce sync.Once
	file_cloud_v1_iam_api_token_proto_rawDescData []byte
)

func file_cloud_v1_iam_api_token_proto_rawDescGZIP() []byte {
	file_cloud_v1_iam_api_token_proto_rawDescOnce.Do(func() {
		file_cloud_v1_iam_api_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_v1_iam_api_token_proto_rawDesc), len(file_cloud_v1_iam_api_token_proto_rawDesc)))
	})
	return file_cloud_v1_iam_api_token_proto_rawDescData
}

var file_cloud_v1_iam_api_token_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cloud_v1_iam_api_token_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cloud_v1_iam_api_token_proto_goTypes = []any{
	(ApiTokenScope)(0),                  // 0: cloud.v1.iam.ApiTokenScope
	(*ApiTokenId)(nil),                  // 1: cloud.v1.iam.ApiTokenId
	(*ApiToken)(nil),                    // 2: cloud.v1.iam.ApiToken
	(*CreateApiTokenRequest)(nil),       // 3: cloud.v1.iam.CreateApiTokenRequest
	(*CreateApiTokenResponse)(nil),      // 4: cloud.v1.iam.CreateApiTokenResponse
	(*UpdateApiTokenExpiryRequest)(nil), // 5: cloud.v1.iam.UpdateApiTokenExpiryRequest
	(*ApiToken_List)(nil),               // 6: cloud.v1.iam.ApiToken.List
	(*TenantId)(nil),                    // 7: cloud.v1.iam.TenantId
	(*UserId)(nil),                      // 8: cloud.v1.iam.UserId
	(*common.Timestamps)(nil),           // 9: cloud.v1.common.Timestamps
	(*timestamppb.Timestamp)(nil),       // 10: google.protobuf.Timestamp
}
var file_cloud_v1_iam_api_token_proto_depIdxs = []int32{
	1,  // 0: cloud.v1.iam.ApiToken.id:type_name -> cloud.v1.iam.ApiTokenId
	7,  // 1: cloud.v1.iam.ApiToken.tenant_id:type_name -> cloud.v1.iam.TenantId
	8,  // 2: cloud.v1.iam.ApiToken.created_by:type_name -> cloud.v1.iam.UserId
	9,  // 3: cloud.v1.iam.ApiToken.timestamps:type_name -> cloud.v1.common.Timestamps
	0,  // 4: cloud.v1.iam.ApiToken.scopes:type_name -> cloud.v1.iam.ApiTokenScope
	10, // 5: cloud.v1.iam.ApiToken.expires_at:type_name -> google.protobuf.Timestamp
	10, // 6: cloud.v1.iam.ApiToken.last_used_at:type_name -> google.protobuf.Timestamp
	2,  // 7: cloud.v1.iam.CreateApiTokenRequest.token:type_name -> cloud.v1.iam.ApiToken
	2,  // 8: cloud.v1.iam.CreateApiTokenResponse.token:type_name -> cloud.v1.iam.ApiToken
	1,  // 9: cloud.v1.iam.UpdateApiTokenExpiryRequest.id:type_name -> cloud.v1.iam.ApiTokenId
	10, // 10: cloud.v1.iam.UpdateApiTokenExpiryRequest.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 11: cloud.v1.iam.ApiToken.List.api_tokens:type_name -> cloud.v1.iam.ApiToken
	3,  // 12: cloud.v1.iam.ApiTokenService.CreateApiToken:input_type -> cloud.v1.iam.CreateApiTokenRequest
	1,  // 13: cloud.v1.iam.ApiTokenService.RevokeApiToken:input_type -> cloud.v1.iam.ApiTokenId
	1,  // 14: cloud.v1.iam.ApiTokenService.GetApiToken:input_type -> cloud.v1.iam.ApiTokenId
	7,  // 15: cloud.v1.iam.ApiTokenService.ListApiTokens:input_type -> cloud.v1.iam.TenantId
	5,  // 16: cloud.v1.iam.ApiTokenService.UpdateApiTokenExpiry:input_type -> cloud.v1.iam.UpdateApiTokenExpiryRequest
	4,  // 17: cloud.v1.iam.ApiTokenService.CreateApiToken:output_type -> cloud.v1.iam.CreateApiTokenResponse
	2,  // 18: cloud.v1.iam.ApiTokenService.RevokeApiToken:output_type -> cloud.v1.iam.ApiToken
	2,  // 19: cloud.v1.iam.ApiTokenService.GetApiToken:output_type -> cloud.v1.iam.ApiToken
	6,  // 20: cloud.v1.iam.ApiTokenService.ListApiTokens:output_type -> cloud.v1.iam.ApiToken.List
	2,  // 21: cloud.v1.iam.ApiTokenService.UpdateApiTokenExpiry:output_type -> cloud.v1.iam.ApiToken
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_cloud_v1_iam_api_token_proto_init() }
func file_cloud_v1_iam_api_token_proto_init() {
	if File_cloud_v1_iam_api_token_proto != nil {
		return
	}
	file_cloud_v1_iam_tenant_proto_init()
	file_cloud_v1_iam_user_proto_init()
	file_cloud_v1_iam_api_token_proto_msgTypes[1].OneofWrappers = []any{}
	file_cloud_v1_iam_api_token_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_v1_iam_api_token_proto_rawDesc), len(file_cloud_v1_iam_api_token_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cloud_v1_iam_api_token_proto_goTypes,
		DependencyIndexes: file_cloud_v1_iam_api_token_proto_depIdxs,
		EnumInfos:         file_cloud_v1_iam_api_token_proto_enumTypes,
		MessageInfos:      file_cloud_v1_iam_api_token_proto_msgTypes,
	}.Build()
	File_cloud_v1_iam_api_token_proto = out.File
	file_cloud_v1_iam_api_token_proto_goTypes = nil
	file_cloud_v1_iam_api_token_proto_depIdxs = nil
}
