// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: cloud/v1/iam/membership.proto

package iam

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// membership.proto wires the model together. A Membership is the join that
// grants an Account access inside a Tenant by attaching one or more Roles. It
// is the ONLY path to tenant access for a non-admin account: no Membership,
// no entry.
//
// Effective authorization for a caller in a tenant = the union of the
// Permissions of every Role referenced here (plus any SCOPE_PLATFORM roles the
// account holds independently, and the full-access shortcut when
// Account.is_admin is true).
type Membership struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the stable, server-assigned unique identifier (e.g. UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// account_id references the Account being granted access.
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// tenant_id references the Tenant the access is scoped to.
	TenantId string `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// role_ids references Role.id values granted by this membership. At least
	// one role is required — a membership with no roles grants nothing and
	// should not exist. The referenced roles are expected to be either
	// SCOPE_TENANT roles of this same tenant_id or SCOPE_PLATFORM roles;
	// cross-tenant role references are rejected by the service layer.
	RoleIds []string `protobuf:"bytes,4,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	// created_at is when the membership was first created (server clock).
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at is when the membership was last mutated (server clock).
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Membership) Reset() {
	*x = Membership{}
	mi := &file_cloud_v1_iam_membership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_iam_membership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Membership.ProtoReflect.Descriptor instead.
func (*Membership) Descriptor() ([]byte, []int) {
	return file_cloud_v1_iam_membership_proto_rawDescGZIP(), []int{0}
}

func (x *Membership) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Membership) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Membership) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Membership) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *Membership) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Membership) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_cloud_v1_iam_membership_proto protoreflect.FileDescriptor

const file_cloud_v1_iam_membership_proto_rawDesc = "" +
	"\n" +
	"\x1dcloud/v1/iam/membership.proto\x12\fcloud.v1.iam\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\x9c\x02\n" +
	"\n" +
	"Membership\x12\x19\n" +
	"\x02id\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18@R\x02id\x12(\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18@R\taccountId\x12&\n" +
	"\ttenant_id\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18@R\btenantId\x12+\n" +
	"\brole_ids\x18\x04 \x03(\tB\x10\xfaB\r\x92\x01\n" +
	"\b\x01\"\x06r\x04\x10\x01\x18@R\aroleIds\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtBAZ?github.com/stroppy-io/stroppy-cloud/internal/proto/cloud/v1/iamb\x06proto3"

var (
	file_cloud_v1_iam_membership_proto_rawDescOnce sync.Once
	file_cloud_v1_iam_membership_proto_rawDescData []byte
)

func file_cloud_v1_iam_membership_proto_rawDescGZIP() []byte {
	file_cloud_v1_iam_membership_proto_rawDescOnce.Do(func() {
		file_cloud_v1_iam_membership_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_v1_iam_membership_proto_rawDesc), len(file_cloud_v1_iam_membership_proto_rawDesc)))
	})
	return file_cloud_v1_iam_membership_proto_rawDescData
}

var file_cloud_v1_iam_membership_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cloud_v1_iam_membership_proto_goTypes = []any{
	(*Membership)(nil),            // 0: cloud.v1.iam.Membership
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_cloud_v1_iam_membership_proto_depIdxs = []int32{
	1, // 0: cloud.v1.iam.Membership.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: cloud.v1.iam.Membership.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cloud_v1_iam_membership_proto_init() }
func file_cloud_v1_iam_membership_proto_init() {
	if File_cloud_v1_iam_membership_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_v1_iam_membership_proto_rawDesc), len(file_cloud_v1_iam_membership_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloud_v1_iam_membership_proto_goTypes,
		DependencyIndexes: file_cloud_v1_iam_membership_proto_depIdxs,
		MessageInfos:      file_cloud_v1_iam_membership_proto_msgTypes,
	}.Build()
	File_cloud_v1_iam_membership_proto = out.File
	file_cloud_v1_iam_membership_proto_goTypes = nil
	file_cloud_v1_iam_membership_proto_depIdxs = nil
}
