syntax = "proto3";

package cloud.v1.models;

import "cloud/v1/common/tags.proto";
import "cloud/v1/domain/database.proto";
import "cloud/v1/domain/topology.proto";
import "cloud/v1/domain/workload.proto";
import "cloud/v1/models/common.proto";
import "goplain/goplain.proto";
import "ratelproto/ratelproto.proto";
import "validate/validate.proto";

option go_package = "github.com/stroppy-io/stroppy-cloud/internal/proto/cloud/v1/models";


message Preset {
    option (goplain.message).generate = true;
    option (ratel.table) = {
        generate: true
        table_name: "presets"
    };
    models.Entity entity = 1 [(goplain.field).embed = true];
    models.Own owned = 2 [(goplain.field).embed = true];
    common.Tags tags = 3 [
        (goplain.field).embed = true
    ];
    message WorkloadPreset {
        domain.Workload workload = 4 [(validate.rules).message.required = true];
        domain.Topology topology = 5 [(validate.rules).message.required = true];
    }
    message DatabasePreset {
        domain.Database workload = 4 [(validate.rules).message.required = true];
        domain.Topology topology = 5 [(validate.rules).message.required = true];
    }
    oneof preset {
        option (goplain.oneof).embed = true;
        option (validate.required) = true;
        WorkloadPreset workload_preset = 4 [
            (goplain.field).serialize = true,
            (validate.rules).message.required = true
        ];
        DatabasePreset database_preset = 5 [
            (goplain.field).serialize = true,
            (validate.rules).message.required = true
        ];
    }
}