syntax = "proto3";

package cloud.v1.api;

import "v1/iam/member.proto";
import "v1/iam/tenant.proto";
import "v1/iam/user.proto";
import "validate/validate.proto";

option go_package = "github.com/stroppy-io/stroppy-cloud/internal/proto/v1/api";


message AddMemberRequest {
    cloud.v1.iam.TenantId tenant_id = 1 [(validate.rules).message = {required: true}];
    cloud.v1.iam.UserId   user_id   = 2 [(validate.rules).message = {required: true}];
    cloud.v1.iam.TenantRole role    = 3 [(validate.rules).enum = {defined_only: true, not_in: [0]}];
}

message UpdateMemberRoleRequest {
    cloud.v1.iam.TenantMemberId member_id = 1 [(validate.rules).message = {required: true}];
    cloud.v1.iam.TenantRole role          = 2 [(validate.rules).enum = {defined_only: true, not_in: [0]}];
}


service TenantMemberService {
    rpc AddMember        (AddMemberRequest)            returns (cloud.v1.iam.TenantMember)      { option idempotency_level = IDEMPOTENT; }
    rpc UpdateMemberRole (UpdateMemberRoleRequest)     returns (cloud.v1.iam.TenantMember)      { option idempotency_level = IDEMPOTENT; }
    rpc RemoveMember     (cloud.v1.iam.TenantMemberId)    returns (cloud.v1.iam.TenantMember)      { option idempotency_level = IDEMPOTENT; }
    rpc ListByTenant     (cloud.v1.iam.TenantId)          returns (cloud.v1.iam.TenantMember.List) { option idempotency_level = NO_SIDE_EFFECTS; }
    rpc ListByUser       (cloud.v1.iam.UserId)            returns (cloud.v1.iam.TenantMember.List) { option idempotency_level = NO_SIDE_EFFECTS; }
}
