syntax = "proto3";

package cloud.v1.api;

import "v1/catalog/database.proto";
import "v1/catalog/package.proto";
import "google/protobuf/field_mask.proto";
import "v1/iam/tenant.proto";
import "validate/validate.proto";

option go_package = "github.com/stroppy-io/stroppy-cloud/internal/proto/v1/api";


message CreatePackageRequest {
    cloud.v1.catalog.Package package = 1 [(validate.rules).message = {required: true}];
}

message UpdatePackageRequest {
    cloud.v1.catalog.Package package = 1 [(validate.rules).message = {required: true}];
    google.protobuf.FieldMask update_mask = 2 [(validate.rules).message = {required: true}];
}

message ListPackagesRequest {
    optional cloud.v1.iam.TenantId tenant_id = 1;       // null = also include builtins
    optional cloud.v1.catalog.Database.Kind db_kind = 2;
}


service PackageService {
    rpc CreatePackage (CreatePackageRequest) returns (cloud.v1.catalog.Package)      { option idempotency_level = IDEMPOTENT; }
    rpc UpdatePackage (UpdatePackageRequest) returns (cloud.v1.catalog.Package)      { option idempotency_level = IDEMPOTENT; }
    rpc DeletePackage (cloud.v1.catalog.PackageId) returns (cloud.v1.catalog.Package)   { option idempotency_level = IDEMPOTENT; }
    rpc GetPackage    (cloud.v1.catalog.PackageId) returns (cloud.v1.catalog.Package)   { option idempotency_level = NO_SIDE_EFFECTS; }
    rpc ListPackages  (ListPackagesRequest)     returns (cloud.v1.catalog.Package.List) { option idempotency_level = NO_SIDE_EFFECTS; }
    rpc ClonePackage  (cloud.v1.catalog.PackageId) returns (cloud.v1.catalog.Package)      { option idempotency_level = IDEMPOTENT; }
}
