syntax = "proto3";

package cloud.v1.api;

import "v1/catalog/settings.proto";
import "v1/iam/tenant.proto";
import "validate/validate.proto";

option go_package = "github.com/stroppy-io/stroppy-cloud/internal/proto/v1/api";

message ListSettingsRequest {
    cloud.v1.iam.TenantId tenant_id = 1 [(validate.rules).message = {required: true}];
}

message SetSettingRequest {
    cloud.v1.catalog.SettingsItemId id = 2 [(validate.rules).message = {required: true}];
    cloud.v1.catalog.SettingsItem.Value value = 3 [(validate.rules).message = {required: true}];
}

message SetSettingManyRequest {
    repeated SetSettingRequest settings = 2 [(validate.rules).message = {required: true}];
}

service SettingsService {
    rpc ListSettings (ListSettingsRequest) returns (cloud.v1.catalog.SettingsItem.List) {
        option idempotency_level = NO_SIDE_EFFECTS;
    }
    rpc SetSetting (SetSettingRequest) returns (cloud.v1.catalog.SettingsItem) {
        option idempotency_level = IDEMPOTENT;
    }
    rpc SetSettingMany (SetSettingManyRequest) returns (cloud.v1.catalog.SettingsItem.List) {
        option idempotency_level = IDEMPOTENT;
    }
}

