syntax = "proto3";

package cloud.v1.api;

import "google/protobuf/field_mask.proto";
import "v1/iam/tenant.proto";
import "v1/testing/test_run.proto";
import "v1/testing/test_run_template.proto";
import "validate/validate.proto";

option go_package = "github.com/stroppy-io/stroppy-cloud/internal/proto/v1/api";


message CreateTestRunTemplateRequest {
    cloud.v1.testing.TestRunTemplate template = 1 [(validate.rules).message = {required: true}];
}

message UpdateTestRunTemplateRequest {
    cloud.v1.testing.TestRunTemplate template = 1 [(validate.rules).message = {required: true}];
    google.protobuf.FieldMask update_mask = 2 [(validate.rules).message = {required: true}];
}


service TestRunTemplateService {
    rpc CreateTestRunTemplate (CreateTestRunTemplateRequest) returns (cloud.v1.testing.TestRunTemplate)      { option idempotency_level = IDEMPOTENT; }
    rpc UpdateTestRunTemplate (UpdateTestRunTemplateRequest) returns (cloud.v1.testing.TestRunTemplate)      { option idempotency_level = IDEMPOTENT; }
    rpc DeleteTestRunTemplate (cloud.v1.testing.TestRunTemplateId) returns (cloud.v1.testing.TestRunTemplate)   { option idempotency_level = IDEMPOTENT; }
    rpc GetTestRunTemplate    (cloud.v1.testing.TestRunTemplateId) returns (cloud.v1.testing.TestRunTemplate)   { option idempotency_level = NO_SIDE_EFFECTS; }
    rpc ListTestRunTemplates  (cloud.v1.iam.TenantId)              returns (cloud.v1.testing.TestRunTemplate.List) { option idempotency_level = NO_SIDE_EFFECTS; }

    /* InstantiateTestRun — create a new TestRun from this template. */
    rpc InstantiateTestRun (cloud.v1.testing.TestRunTemplateId) returns (cloud.v1.testing.TestRun) { option idempotency_level = IDEMPOTENT; }
}
