// Code generated by protoc-gen-go-jx. DO NOT EDIT.

package common

import (
	fmt "fmt"
	jx "github.com/go-faster/jx"
	jxpb "github.com/gopherex/protoc-gen-go-jx/jxpb"
	schemapb "github.com/stroppy-io/schemapb/schemapb"
)

func (m *File) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.Info != nil {
		e.FieldStart("info")
		m.Info.Encode(e)
	}
	if m.Append != false {
		e.FieldStart("append")
		e.Bool(m.Append)
	}
	switch v := m.Content.(type) {
	case *File_Text:
		e.FieldStart("text")
		e.Str(v.Text)
	case *File_Bytes:
		e.FieldStart("bytes")
		jxpb.EncBytes(e, v.Bytes)
	case *File_AsRef_:
		e.FieldStart("asRef")
		v.AsRef.Encode(e)
	}
	e.ObjEnd()
}

func (m *File) Decode(d *jx.Decoder) error {
	seen := map[string]bool{}
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "info":
			if seen["Info"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Info"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Info = &File_Info{}
			if err := m.Info.Decode(d); err != nil {
				return err
			}
			return nil
		case "append":
			if seen["Append"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Append"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Bool()
			if err != nil {
				return err
			}
			m.Append = v
			return nil
		case "text":
			if seen["oneof:Content"] {
				return fmt.Errorf("multiple keys for oneof content")
			}
			seen["oneof:Content"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			val, err := d.Str()
			if err != nil {
				return err
			}
			m.Content = &File_Text{Text: val}
			return nil
		case "bytes":
			if seen["oneof:Content"] {
				return fmt.Errorf("multiple keys for oneof content")
			}
			seen["oneof:Content"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			val, err := jxpb.DecBytes(d)
			if err != nil {
				return err
			}
			m.Content = &File_Bytes{Bytes: val}
			return nil
		case "asRef", "as_ref":
			if seen["oneof:Content"] {
				return fmt.Errorf("multiple keys for oneof content")
			}
			seen["oneof:Content"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			w := &File_AsRef_{}
			w.AsRef = &File_AsRef{}
			if err := w.AsRef.Decode(d); err != nil {
				return err
			}
			m.Content = w
			return nil
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *File) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *File) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *File_Info) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.Path != "" {
		e.FieldStart("path")
		e.Str(m.Path)
	}
	if m.Mode != 0 {
		e.FieldStart("mode")
		e.UInt32(m.Mode)
	}
	if m.Owner != "" {
		e.FieldStart("owner")
		e.Str(m.Owner)
	}
	if m.Group != "" {
		e.FieldStart("group")
		e.Str(m.Group)
	}
	if m.CreateParents != false {
		e.FieldStart("createParents")
		e.Bool(m.CreateParents)
	}
	e.ObjEnd()
}

func (m *File_Info) Decode(d *jx.Decoder) error {
	seen := map[string]bool{}
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "path":
			if seen["Path"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Path"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.Path = v
			return nil
		case "mode":
			if seen["Mode"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Mode"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := jxpb.DecUint32(d)
			if err != nil {
				return err
			}
			m.Mode = v
			return nil
		case "owner":
			if seen["Owner"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Owner"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.Owner = v
			return nil
		case "group":
			if seen["Group"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Group"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.Group = v
			return nil
		case "createParents", "create_parents":
			if seen["CreateParents"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["CreateParents"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Bool()
			if err != nil {
				return err
			}
			m.CreateParents = v
			return nil
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *File_Info) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *File_Info) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *File_AsRef) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.Uri != "" {
		e.FieldStart("uri")
		e.Str(m.Uri)
	}
	if m.Checksum != "" {
		e.FieldStart("checksum")
		e.Str(m.Checksum)
	}
	e.ObjEnd()
}

func (m *File_AsRef) Decode(d *jx.Decoder) error {
	seen := map[string]bool{}
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "uri":
			if seen["Uri"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Uri"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.Uri = v
			return nil
		case "checksum":
			if seen["Checksum"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Checksum"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.Checksum = v
			return nil
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *File_AsRef) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *File_AsRef) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}

func (m *BakedFile) Encode(e *jx.Encoder) {
	if m == nil {
		e.ObjStart()
		e.ObjEnd()
		return
	}
	e.ObjStart()
	if m.File != nil {
		e.FieldStart("file")
		m.File.Encode(e)
	}
	if m.ResolverName != "" {
		e.FieldStart("resolverName")
		e.Str(m.ResolverName)
	}
	if m.Data != nil {
		e.FieldStart("data")
		jxpb.EncMessage(e, m.Data)
	}
	e.ObjEnd()
}

func (m *BakedFile) Decode(d *jx.Decoder) error {
	seen := map[string]bool{}
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "file":
			if seen["File"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["File"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.File = &File{}
			if err := m.File.Decode(d); err != nil {
				return err
			}
			return nil
		case "resolverName", "resolver_name":
			if seen["ResolverName"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["ResolverName"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.ResolverName = v
			return nil
		case "data":
			if seen["Data"] {
				return fmt.Errorf("duplicate field %q", key)
			}
			seen["Data"] = true
			if d.Next() == jx.Null {
				return d.Null()
			}
			m.Data = &schemapb.Baked{}
			if err := jxpb.DecMessage(d, m.Data); err != nil {
				return err
			}
			return nil
		default:
			return fmt.Errorf("unknown field %q", key)
		}
	})
}

func (m *BakedFile) MarshalJSON() ([]byte, error) {
	var e jx.Encoder
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *BakedFile) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return m.Decode(d)
}
