syntax = "proto3";

package cloud.v1.api.ui;

import "cloud/v1/common/tags.proto";
import "cloud/v1/domain/database.proto";
import "cloud/v1/models/common.proto";
import "cloud/v1/models/database_preset.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/field_mask.proto";
import "validate/validate.proto";

option go_package = "github.com/stroppy-io/stroppy-cloud/internal/proto/cloud/v1/api/ui";

message ListDatabasePresetRequest {
    models.TenantId tenant_id = 1 [(validate.rules).message.required = true];
    optional models.AccountId owner_account_id = 2;
    optional common.Tags tags = 3;
    optional domain.Database.Kind kind = 4;
}

message CreatePresetRequest {
    models.TenantId tenant_id = 1 [(validate.rules).message.required = true];
    domain.Database database = 2 [(validate.rules).message.required = true];
    domain.Topology topology = 6 [
        (goplain.field).serialize = true,
        (validate.rules).message.required = true
    ];
}

message UpdatePresetRequest {
    models.DatabasePreset preset = 1 [(validate.rules).message.required = true];
    google.protobuf.FieldMask update_mask = 2 [(validate.rules).message.required = true];
}

service DatabasePresetService {
    rpc CreatePreset (CreatePresetRequest) returns (models.DatabasePreset) {option idempotency_level = NO_SIDE_EFFECTS;};
    rpc UpdatePreset (UpdatePresetRequest) returns (models.DatabasePreset) {option idempotency_level = IDEMPOTENT;};
    rpc DeletePreset (models.DatabasePresetId) returns (google.protobuf.Empty) {option idempotency_level = IDEMPOTENT;};
    rpc ClonePreset (models.DatabasePresetId) returns (models.DatabasePreset) {option idempotency_level = IDEMPOTENT;};
}