// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts,import_extension=ts"
// @generated from file cloud/v1/api/ui/apitoken.proto (package cloud.v1.api.ui, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateApiTokenRequest, CreateApiTokenResponse, ListApiTokensRequest, RevokeApiTokenRequest } from "./apitoken_pbts";
import { Empty, MethodIdempotency, MethodKind } from "@bufbuild/protobuf";
import { ApiToken_List } from "../../models/apitoken_pbts";

/**
 * @generated from service cloud.v1.api.ui.ApiTokenService
 */
export const ApiTokenService = {
  typeName: "cloud.v1.api.ui.ApiTokenService",
  methods: {
    /**
     * @generated from rpc cloud.v1.api.ui.ApiTokenService.CreateApiToken
     */
    createApiToken: {
      name: "CreateApiToken",
      I: CreateApiTokenRequest,
      O: CreateApiTokenResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.Idempotent,
    },
    /**
     * @generated from rpc cloud.v1.api.ui.ApiTokenService.ListApiTokens
     */
    listApiTokens: {
      name: "ListApiTokens",
      I: ListApiTokensRequest,
      O: ApiToken_List,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * @generated from rpc cloud.v1.api.ui.ApiTokenService.RevokeApiToken
     */
    revokeApiToken: {
      name: "RevokeApiToken",
      I: RevokeApiTokenRequest,
      O: Empty,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.Idempotent,
    },
  }
} as const;

