syntax = "proto3";

package cloud.api;

import "google/protobuf/field_mask.proto";
import "models/account.proto";
import "models/tenant.proto";
import "validate/validate.proto";

option go_package = "github.com/stroppy-io/stroppy-cloud/internal/proto/api";

message CreateAccountRequest {
    models.TenantId tenant_id = 1;
    models.Account account = 2 [(validate.rules).message = {required: true}];
    string password = 4 [(validate.rules).string.pattern = '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$'];
}

message UpdateAccountRequest {
    models.Account account = 1 [(validate.rules).message = {required: true}];
    google.protobuf.FieldMask update_mask = 2 [(validate.rules).message = {required: true}];
    string password = 5 [(validate.rules).string.pattern = '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$'];
}

message UpdatePasswordRequest {
    string old_password = 2 [(validate.rules).string.pattern = '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$'];
    string new_password = 3 [(validate.rules).string.pattern = '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$'];
    string new_password_confirmation = 4 [(validate.rules).string.pattern = '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$'];
}

service AccountService {
    rpc CreateAccount (CreateAccountRequest) returns (models.Account) {
        option idempotency_level = IDEMPOTENT;
    }
    rpc UpdateAccount (UpdateAccountRequest) returns (models.Account) {
        option idempotency_level = IDEMPOTENT;
    }
    rpc DeleteAccount (models.AccountId) returns (models.Account) {
        option idempotency_level = IDEMPOTENT;
    }
    rpc UpdatePassword (UpdatePasswordRequest) returns (models.Account) {
        option idempotency_level = IDEMPOTENT;
    }
}