syntax = "proto3";

package cloud.models;

import "goplain/goplain.proto";
import "ratelproto/ratelproto.proto";
import "validate/validate.proto";

option go_package = "github.com/stroppy-io/stroppy-cloud/internal/proto/models";


message AgentId { option (goplain.message) = {generate: true, type_alias: true}; string value = 1 [(validate.rules).string.len = 26]; }
/* Represents an agent instance with metadata. */
message Agent {
    /* Collection of agents. */
    message List {repeated Agent agents = 1;}
    option (goplain.message).generate = true;
    option (ratel.table) = {
        generate: true
        table_name: "agents"
    };

    AgentId id = 1 [
        (ratel.column) = {constraints: {primary_key: true}},
        (validate.rules).message = {required: true}
    ];
    optional string name = 2; // Human-readable agent name
}
