// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: cloud/v1/api/ui/apitoken.proto

package ui

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	models "github.com/stroppy-io/stroppy-cloud/internal/proto/cloud/v1/models"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = models.TenantMember_Role(0)
)

// Validate checks the field values on CreateApiTokenRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateApiTokenRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateApiTokenRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateApiTokenRequestMultiError, or nil if none found.
func (m *CreateApiTokenRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateApiTokenRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetTenantId() == nil {
		err := CreateApiTokenRequestValidationError{
			field:  "TenantId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTenantId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateApiTokenRequestValidationError{
					field:  "TenantId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateApiTokenRequestValidationError{
					field:  "TenantId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTenantId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateApiTokenRequestValidationError{
				field:  "TenantId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 255 {
		err := CreateApiTokenRequestValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _CreateApiTokenRequest_Role_NotInLookup[m.GetRole()]; ok {
		err := CreateApiTokenRequestValidationError{
			field:  "Role",
			reason: "value must not be in list [ROLE_UNSPECIFIED ROLE_OWNER]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := models.TenantMember_Role_name[int32(m.GetRole())]; !ok {
		err := CreateApiTokenRequestValidationError{
			field:  "Role",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.ExpiresAt != nil {

		if all {
			switch v := interface{}(m.GetExpiresAt()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CreateApiTokenRequestValidationError{
						field:  "ExpiresAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CreateApiTokenRequestValidationError{
						field:  "ExpiresAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetExpiresAt()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreateApiTokenRequestValidationError{
					field:  "ExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return CreateApiTokenRequestMultiError(errors)
	}

	return nil
}

// CreateApiTokenRequestMultiError is an error wrapping multiple validation
// errors returned by CreateApiTokenRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateApiTokenRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateApiTokenRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateApiTokenRequestMultiError) AllErrors() []error { return m }

// CreateApiTokenRequestValidationError is the validation error returned by
// CreateApiTokenRequest.Validate if the designated constraints aren't met.
type CreateApiTokenRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateApiTokenRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateApiTokenRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateApiTokenRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateApiTokenRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateApiTokenRequestValidationError) ErrorName() string {
	return "CreateApiTokenRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateApiTokenRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateApiTokenRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateApiTokenRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateApiTokenRequestValidationError{}

var _CreateApiTokenRequest_Role_NotInLookup = map[models.TenantMember_Role]struct{}{
	0: {},
	3: {},
}

// Validate checks the field values on CreateApiTokenResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateApiTokenResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateApiTokenResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateApiTokenResponseMultiError, or nil if none found.
func (m *CreateApiTokenResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateApiTokenResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetToken()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateApiTokenResponseValidationError{
					field:  "Token",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateApiTokenResponseValidationError{
					field:  "Token",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetToken()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateApiTokenResponseValidationError{
				field:  "Token",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if l := utf8.RuneCountInString(m.GetSecret()); l < 1 || l > 128 {
		err := CreateApiTokenResponseValidationError{
			field:  "Secret",
			reason: "value length must be between 1 and 128 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateApiTokenResponseMultiError(errors)
	}

	return nil
}

// CreateApiTokenResponseMultiError is an error wrapping multiple validation
// errors returned by CreateApiTokenResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateApiTokenResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateApiTokenResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateApiTokenResponseMultiError) AllErrors() []error { return m }

// CreateApiTokenResponseValidationError is the validation error returned by
// CreateApiTokenResponse.Validate if the designated constraints aren't met.
type CreateApiTokenResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateApiTokenResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateApiTokenResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateApiTokenResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateApiTokenResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateApiTokenResponseValidationError) ErrorName() string {
	return "CreateApiTokenResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateApiTokenResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateApiTokenResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateApiTokenResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateApiTokenResponseValidationError{}

// Validate checks the field values on ListApiTokensRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListApiTokensRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListApiTokensRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListApiTokensRequestMultiError, or nil if none found.
func (m *ListApiTokensRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListApiTokensRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetTenantId() == nil {
		err := ListApiTokensRequestValidationError{
			field:  "TenantId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTenantId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListApiTokensRequestValidationError{
					field:  "TenantId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListApiTokensRequestValidationError{
					field:  "TenantId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTenantId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListApiTokensRequestValidationError{
				field:  "TenantId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if _, ok := ListApiTokensRequest_SortField_name[int32(m.GetSortField())]; !ok {
		err := ListApiTokensRequestValidationError{
			field:  "SortField",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := models.SortOrder_name[int32(m.GetOrder())]; !ok {
		err := ListApiTokensRequestValidationError{
			field:  "Order",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetPage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListApiTokensRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListApiTokensRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListApiTokensRequestValidationError{
				field:  "Page",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetTags()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListApiTokensRequestValidationError{
					field:  "Tags",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListApiTokensRequestValidationError{
					field:  "Tags",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTags()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListApiTokensRequestValidationError{
				field:  "Tags",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.Search != nil {

		if utf8.RuneCountInString(m.GetSearch()) > 256 {
			err := ListApiTokensRequestValidationError{
				field:  "Search",
				reason: "value length must be at most 256 runes",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.Role != nil {

		if _, ok := models.TenantMember_Role_name[int32(m.GetRole())]; !ok {
			err := ListApiTokensRequestValidationError{
				field:  "Role",
				reason: "value must be one of the defined enum values",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.Expired != nil {
		// no validation rules for Expired
	}

	if len(errors) > 0 {
		return ListApiTokensRequestMultiError(errors)
	}

	return nil
}

// ListApiTokensRequestMultiError is an error wrapping multiple validation
// errors returned by ListApiTokensRequest.ValidateAll() if the designated
// constraints aren't met.
type ListApiTokensRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListApiTokensRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListApiTokensRequestMultiError) AllErrors() []error { return m }

// ListApiTokensRequestValidationError is the validation error returned by
// ListApiTokensRequest.Validate if the designated constraints aren't met.
type ListApiTokensRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListApiTokensRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListApiTokensRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListApiTokensRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListApiTokensRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListApiTokensRequestValidationError) ErrorName() string {
	return "ListApiTokensRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListApiTokensRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListApiTokensRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListApiTokensRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListApiTokensRequestValidationError{}

// Validate checks the field values on ListApiTokensResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListApiTokensResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListApiTokensResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListApiTokensResponseMultiError, or nil if none found.
func (m *ListApiTokensResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListApiTokensResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetApiTokens() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListApiTokensResponseValidationError{
						field:  fmt.Sprintf("ApiTokens[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListApiTokensResponseValidationError{
						field:  fmt.Sprintf("ApiTokens[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListApiTokensResponseValidationError{
					field:  fmt.Sprintf("ApiTokens[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPageInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListApiTokensResponseValidationError{
					field:  "PageInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListApiTokensResponseValidationError{
					field:  "PageInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPageInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListApiTokensResponseValidationError{
				field:  "PageInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListApiTokensResponseMultiError(errors)
	}

	return nil
}

// ListApiTokensResponseMultiError is an error wrapping multiple validation
// errors returned by ListApiTokensResponse.ValidateAll() if the designated
// constraints aren't met.
type ListApiTokensResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListApiTokensResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListApiTokensResponseMultiError) AllErrors() []error { return m }

// ListApiTokensResponseValidationError is the validation error returned by
// ListApiTokensResponse.Validate if the designated constraints aren't met.
type ListApiTokensResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListApiTokensResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListApiTokensResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListApiTokensResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListApiTokensResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListApiTokensResponseValidationError) ErrorName() string {
	return "ListApiTokensResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListApiTokensResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListApiTokensResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListApiTokensResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListApiTokensResponseValidationError{}

// Validate checks the field values on RevokeApiTokenRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RevokeApiTokenRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RevokeApiTokenRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RevokeApiTokenRequestMultiError, or nil if none found.
func (m *RevokeApiTokenRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RevokeApiTokenRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetTenantId() == nil {
		err := RevokeApiTokenRequestValidationError{
			field:  "TenantId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTenantId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RevokeApiTokenRequestValidationError{
					field:  "TenantId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RevokeApiTokenRequestValidationError{
					field:  "TenantId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTenantId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RevokeApiTokenRequestValidationError{
				field:  "TenantId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetId() == nil {
		err := RevokeApiTokenRequestValidationError{
			field:  "Id",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RevokeApiTokenRequestValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RevokeApiTokenRequestValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RevokeApiTokenRequestValidationError{
				field:  "Id",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RevokeApiTokenRequestMultiError(errors)
	}

	return nil
}

// RevokeApiTokenRequestMultiError is an error wrapping multiple validation
// errors returned by RevokeApiTokenRequest.ValidateAll() if the designated
// constraints aren't met.
type RevokeApiTokenRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RevokeApiTokenRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RevokeApiTokenRequestMultiError) AllErrors() []error { return m }

// RevokeApiTokenRequestValidationError is the validation error returned by
// RevokeApiTokenRequest.Validate if the designated constraints aren't met.
type RevokeApiTokenRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RevokeApiTokenRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RevokeApiTokenRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RevokeApiTokenRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RevokeApiTokenRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RevokeApiTokenRequestValidationError) ErrorName() string {
	return "RevokeApiTokenRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RevokeApiTokenRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRevokeApiTokenRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RevokeApiTokenRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RevokeApiTokenRequestValidationError{}
