// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: cloud/v1/api/ui/webhook.proto

package ui

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateWebhookRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateWebhookRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateWebhookRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateWebhookRequestMultiError, or nil if none found.
func (m *CreateWebhookRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateWebhookRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetTenantId() == nil {
		err := CreateWebhookRequestValidationError{
			field:  "TenantId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTenantId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateWebhookRequestValidationError{
					field:  "TenantId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateWebhookRequestValidationError{
					field:  "TenantId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTenantId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateWebhookRequestValidationError{
				field:  "TenantId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetWebhook() == nil {
		err := CreateWebhookRequestValidationError{
			field:  "Webhook",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetWebhook()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateWebhookRequestValidationError{
					field:  "Webhook",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateWebhookRequestValidationError{
					field:  "Webhook",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetWebhook()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateWebhookRequestValidationError{
				field:  "Webhook",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if utf8.RuneCountInString(m.GetSecret()) > 512 {
		err := CreateWebhookRequestValidationError{
			field:  "Secret",
			reason: "value length must be at most 512 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateWebhookRequestMultiError(errors)
	}

	return nil
}

// CreateWebhookRequestMultiError is an error wrapping multiple validation
// errors returned by CreateWebhookRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateWebhookRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateWebhookRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateWebhookRequestMultiError) AllErrors() []error { return m }

// CreateWebhookRequestValidationError is the validation error returned by
// CreateWebhookRequest.Validate if the designated constraints aren't met.
type CreateWebhookRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateWebhookRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateWebhookRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateWebhookRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateWebhookRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateWebhookRequestValidationError) ErrorName() string {
	return "CreateWebhookRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateWebhookRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateWebhookRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateWebhookRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateWebhookRequestValidationError{}

// Validate checks the field values on UpdateWebhookRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateWebhookRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateWebhookRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateWebhookRequestMultiError, or nil if none found.
func (m *UpdateWebhookRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateWebhookRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetTenantId() == nil {
		err := UpdateWebhookRequestValidationError{
			field:  "TenantId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTenantId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateWebhookRequestValidationError{
					field:  "TenantId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateWebhookRequestValidationError{
					field:  "TenantId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTenantId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateWebhookRequestValidationError{
				field:  "TenantId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetWebhook() == nil {
		err := UpdateWebhookRequestValidationError{
			field:  "Webhook",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetWebhook()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateWebhookRequestValidationError{
					field:  "Webhook",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateWebhookRequestValidationError{
					field:  "Webhook",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetWebhook()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateWebhookRequestValidationError{
				field:  "Webhook",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if utf8.RuneCountInString(m.GetSecret()) > 512 {
		err := UpdateWebhookRequestValidationError{
			field:  "Secret",
			reason: "value length must be at most 512 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UpdateWebhookRequestMultiError(errors)
	}

	return nil
}

// UpdateWebhookRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateWebhookRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateWebhookRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateWebhookRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateWebhookRequestMultiError) AllErrors() []error { return m }

// UpdateWebhookRequestValidationError is the validation error returned by
// UpdateWebhookRequest.Validate if the designated constraints aren't met.
type UpdateWebhookRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateWebhookRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateWebhookRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateWebhookRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateWebhookRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateWebhookRequestValidationError) ErrorName() string {
	return "UpdateWebhookRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateWebhookRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateWebhookRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateWebhookRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateWebhookRequestValidationError{}

// Validate checks the field values on ListWebhooksRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListWebhooksRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListWebhooksRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListWebhooksRequestMultiError, or nil if none found.
func (m *ListWebhooksRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListWebhooksRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetTenantId() == nil {
		err := ListWebhooksRequestValidationError{
			field:  "TenantId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTenantId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListWebhooksRequestValidationError{
					field:  "TenantId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListWebhooksRequestValidationError{
					field:  "TenantId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTenantId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListWebhooksRequestValidationError{
				field:  "TenantId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListWebhooksRequestMultiError(errors)
	}

	return nil
}

// ListWebhooksRequestMultiError is an error wrapping multiple validation
// errors returned by ListWebhooksRequest.ValidateAll() if the designated
// constraints aren't met.
type ListWebhooksRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListWebhooksRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListWebhooksRequestMultiError) AllErrors() []error { return m }

// ListWebhooksRequestValidationError is the validation error returned by
// ListWebhooksRequest.Validate if the designated constraints aren't met.
type ListWebhooksRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListWebhooksRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListWebhooksRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListWebhooksRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListWebhooksRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListWebhooksRequestValidationError) ErrorName() string {
	return "ListWebhooksRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListWebhooksRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListWebhooksRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListWebhooksRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListWebhooksRequestValidationError{}

// Validate checks the field values on DeleteWebhookRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteWebhookRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteWebhookRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteWebhookRequestMultiError, or nil if none found.
func (m *DeleteWebhookRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteWebhookRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetTenantId() == nil {
		err := DeleteWebhookRequestValidationError{
			field:  "TenantId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTenantId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeleteWebhookRequestValidationError{
					field:  "TenantId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeleteWebhookRequestValidationError{
					field:  "TenantId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTenantId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeleteWebhookRequestValidationError{
				field:  "TenantId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetId() == nil {
		err := DeleteWebhookRequestValidationError{
			field:  "Id",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeleteWebhookRequestValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeleteWebhookRequestValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeleteWebhookRequestValidationError{
				field:  "Id",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DeleteWebhookRequestMultiError(errors)
	}

	return nil
}

// DeleteWebhookRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteWebhookRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteWebhookRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteWebhookRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteWebhookRequestMultiError) AllErrors() []error { return m }

// DeleteWebhookRequestValidationError is the validation error returned by
// DeleteWebhookRequest.Validate if the designated constraints aren't met.
type DeleteWebhookRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteWebhookRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteWebhookRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteWebhookRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteWebhookRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteWebhookRequestValidationError) ErrorName() string {
	return "DeleteWebhookRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteWebhookRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteWebhookRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteWebhookRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteWebhookRequestValidationError{}

// Validate checks the field values on TestWebhookRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TestWebhookRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TestWebhookRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TestWebhookRequestMultiError, or nil if none found.
func (m *TestWebhookRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TestWebhookRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetTenantId() == nil {
		err := TestWebhookRequestValidationError{
			field:  "TenantId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTenantId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TestWebhookRequestValidationError{
					field:  "TenantId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TestWebhookRequestValidationError{
					field:  "TenantId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTenantId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TestWebhookRequestValidationError{
				field:  "TenantId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetId() == nil {
		err := TestWebhookRequestValidationError{
			field:  "Id",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TestWebhookRequestValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TestWebhookRequestValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TestWebhookRequestValidationError{
				field:  "Id",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return TestWebhookRequestMultiError(errors)
	}

	return nil
}

// TestWebhookRequestMultiError is an error wrapping multiple validation errors
// returned by TestWebhookRequest.ValidateAll() if the designated constraints
// aren't met.
type TestWebhookRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TestWebhookRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TestWebhookRequestMultiError) AllErrors() []error { return m }

// TestWebhookRequestValidationError is the validation error returned by
// TestWebhookRequest.Validate if the designated constraints aren't met.
type TestWebhookRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TestWebhookRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TestWebhookRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TestWebhookRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TestWebhookRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TestWebhookRequestValidationError) ErrorName() string {
	return "TestWebhookRequestValidationError"
}

// Error satisfies the builtin error interface
func (e TestWebhookRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTestWebhookRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TestWebhookRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TestWebhookRequestValidationError{}
