syntax = "proto3";

package cloud.v1.iam;

import "v1/common/timestamps.proto";
import "goplain/goplain.proto";
import "v1/common/identity.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/field_mask.proto";
import "ratelproto/ratelproto.proto";
import "validate/validate.proto";

option go_package = "github.com/stroppy-io/stroppy-cloud/internal/proto/v1/iam";

message TenantId { option (goplain.message) = {generate: true, type_alias: true}; string value = 1 [(validate.rules).string.len = 26]; }
/* Root tenant entity representing an isolated workspace. */
message Tenant {
    /* Container for paginated tenant results. */
    message List {repeated Tenant tenants = 1;}
    option (goplain.message).generate = true;
    option (ratel.table) = {
        generate: true
        table_name: "tenants"
    };
    TenantId id = 1 [
        (ratel.column) = {constraints: {primary_key: true}},
        (validate.rules).message = {required: true}
    ];
    cloud.v1.common.Timestamps timestamps = 2 [(goplain.field).embed = true];
    cloud.v1.common.Identity identity = 3 [(goplain.field).embed = true];
}

message CreateTenantRequest {
    Tenant tenant = 1 [(validate.rules).message = {required: true}];
}

message UpdateTenantRequest {
    Tenant tenant = 1 [(validate.rules).message = {required: true}];
    google.protobuf.FieldMask update_mask = 2 [(validate.rules).message = {required: true}];
}

service TenantService {
    rpc ListMyTenants (google.protobuf.Empty) returns (Tenant.List) {
        option idempotency_level = NO_SIDE_EFFECTS;
    }
    rpc CreateTenant (CreateTenantRequest) returns (Tenant) {
        option idempotency_level = IDEMPOTENT;
    }
    rpc UpdateTenant (UpdateTenantRequest) returns (Tenant) {
        option idempotency_level = IDEMPOTENT;
    }
    rpc DeleteTenant (TenantId) returns (Tenant) {
        option idempotency_level = IDEMPOTENT;
    }
}
