{
 "title": "Stroppy / CockroachDB",
 "description": "CockroachDB metrics dashboard for Stroppy load test runs",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "run_id", "label": "Run" },
   {
    "name": "Instance",
    "label": "Machine",
    "query": "label_values(sql_query_count{stroppy_run_id=\"$run_id\"}, stroppy_machine_id)"
   },
   { "name": "Interval", "query": "30sec,1m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "SQL Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SQL Queries/s",
   "type": "graph",
   "description": "Total SQL queries per second across all nodes.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "queries/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_query_count{stroppy_run_id=\"$run_id\",stroppy_machine_id=~\"$Instance\"}[$Interval]))",
     "legendFormat": "Queries/s"
    }
   ]
  },
  {
   "title": "Transactions/s",
   "type": "graph",
   "description": "SQL transactions per second: committed + aborted.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "txn/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_txn_commit_count{stroppy_run_id=\"$run_id\",stroppy_machine_id=~\"$Instance\"}[$Interval]))",
     "legendFormat": "Commits/s"
    },
    {
     "expr": "sum(rate(sql_txn_abort_count{stroppy_run_id=\"$run_id\",stroppy_machine_id=~\"$Instance\"}[$Interval]))",
     "legendFormat": "Aborts/s"
    }
   ]
  },
  { "title": "Errors & Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "SQL Errors/s",
   "type": "graph",
   "description": "Rate of SQL statement failures per second.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "errors/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_failure_count{stroppy_run_id=\"$run_id\",stroppy_machine_id=~\"$Instance\"}[$Interval]))",
     "legendFormat": "Errors/s"
    }
   ]
  },
  {
   "title": "Open SQL Connections",
   "type": "graph",
   "description": "Total number of open SQL connections across all nodes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "sum(sql_conns{stroppy_run_id=\"$run_id\",stroppy_machine_id=~\"$Instance\"})",
     "legendFormat": "Connections"
    }
   ]
  },
  { "title": "Latency & Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Service Latency p99 (ms)",
   "type": "graph",
   "description": "99th-percentile SQL service latency in milliseconds. The raw metric (sql_service_latency_bucket) is in nanoseconds; divide by 1e6 for ms.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(sql_service_latency_bucket{stroppy_run_id=\"$run_id\",stroppy_machine_id=~\"$Instance\"}[$Interval]))) / 1e6",
     "legendFormat": "p99 latency"
    }
   ]
  },
  {
   "title": "Live Bytes",
   "type": "graph",
   "description": "Total live data bytes stored across all nodes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(livebytes{stroppy_run_id=\"$run_id\",stroppy_machine_id=~\"$Instance\"})",
     "legendFormat": "Live Bytes"
    }
   ]
  }
 ]
}